### ISSUE TITLE
Fail to generate electron application

### ISSUE THREAD

**Issue by zack9433** [bennymeg/nx-electron#1]
version: 8.0.0-alpha.2

![image](https://user-images.githubusercontent.com/1610642/69490560-f846f480-0ec4-11ea-8080-50327cb567d7.png)

**Comment by bennymeg** [comment]
The application name in mandatory, please add it and try again.

We recommend using the following naming scheme (although it is just a suggestion):
frontend: `<app-name>-web` (in your case: 'tp-provision-tool-web')
backend: `<app-name>-app` (in your case: 'tp-provision-tool-app)

**Comment by zack9433** [comment]
![image](https://user-images.githubusercontent.com/1610642/69508146-d0609b00-0f6f-11ea-9ae5-20ff323e2659.png)

**Comment by bennymeg** [comment]
Now you have not provided the frontend name...
You should run `nx g nx-electron:app tp-provision-tool-app  --frontendProject=tp-provision-tool-web`

**Note:**  you have to create you frontend project before hand by invoking
`nx g @nrwl/angular:app tp-provision-tool-web`

Try using[ angular console](https://angularconsole.com/) to invoke schematics, it will help you to avoid this kind of mistakes.

**Comment by zack9433** [comment]
@bennymeg it's working, thx for your tips

**Comment by bennymeg** [comment]
I'm glad I could help.
I've updated the documentation to clear it out for future users as well.
