### ISSUE TITLE
Electron running empty app

### ISSUE THREAD

**Issue by adrianzaorski** [bennymeg/nx-electron#10]
**Describe the bug**
The electron is not serving content from a file.

**To Reproduce**
1. nx serve app-name

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Angular 9, Electron 8

**Additional context**
The `join(__dirname, '..', rendererAppName, 'index.html')` returns `/media/adrian/67c31b98-4b93-45f5-8c32-41f88deb82cd/baggy-chat-frontend/dist/apps/baggy-chat/index.html` which is valid path for that file. I tried with valid HTML structure, but the empty body, also tried with an empty file with one word inside only, however, the output is always the same - shown on the screenshot. The structure of HTML which is served by the electron is always the same ignoring the content of index.html

I followed the steps from the readme: created nx workspace -> generated angular app -> generated electron app from schematic -> built an angular app -> tried to serve electron

**Screenshots**
![image](https://user-images.githubusercontent.com/40486935/75384704-c3d93f00-58de-11ea-9398-82c02ada2090.png)

**Comment by bennymeg** [comment]
If you running development mode, you have served the angular app as well.
If you running production mode, you have build both of them and then package them or make an executable.

Try serving you front end (angular) app and then you back end (electron) app in parallel.
Let me know if everything works for you.

**Comment by adrianzaorski** [comment]
@bennymeg Yeah, it works now. Big thanks for helping me :)
