### ISSUE TITLE
Start electron when the front-end application is available 

### ISSUE THREAD

**Issue by TobiasTao** [bennymeg/nx-electron#103]
**Is your feature request related to a problem? Please describe.**

When i use `nx run-many --target=serve--projects=<frontend-app-name>,<electron-app-name> --parallel`  serving a nx electron application, its blank:
![image](https://user-images.githubusercontent.com/37654563/120926483-a44eda00-c70f-11eb-98c8-5bf7468bd6a5.png)
I need to restart electron to get the application back to normal 
**Describe the solution you'd like**

add deps：
```json

    "wait-on": "^5.3.0"
    "npm-run-all": "^4.1.5",

````

add scripts:

```json

    "start": "run-p ng:start electron:start",
    "ng:start": "ng serve -o",
    "electron:start": "wait-on tcp:4200 && nx run <electron-app-name>:serve",

```

then run `ng start`, everything is fine : )

**Comment by bennymeg** [comment]
Thank you for sharing this approach.
Personally, I think invoking the serve command for each project separately it the way to go.

I will link this issue in the documentation.

**Comment by julianpoemp** [comment]
I'm using the command as workaround:

    nx serve citarlo-web & (sleep 15 && nx serve citarlo-desktop)

You can add it to your `scripts` propertie in package.json e.g. as follows:

    "start:both": "nx serve citarlo-web & (sleep 15 && nx serve citarlo-desktop)"

If your Electron app starts before your frontend app build successfully, just increase the seconds after the `sleep`command.
