### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by seloner** [bennymeg/nx-electron#119]
Hello I am trying to package/make the application but I am having issues.
My project structure is like this 
![image](https://user-images.githubusercontent.com/29483115/138049772-f8643087-aae3-4d11-a56c-de304fb98066.png)
My web project that I want to build from is using nextjs . I am using next export to build the web application .
My dist folder looks like this 
![image](https://user-images.githubusercontent.com/29483115/138049941-4e363f4a-3f82-42a3-ae7b-17db1bd0a9a7.png)
The actual build is inside the  **exported folder** .
The error 
![image](https://user-images.githubusercontent.com/29483115/138050267-bab64beb-8e1d-4083-a21f-9a48ade2f0de.png)
Am I doing the steps wrong ?
First I build the web app with next export .
After I build the electron desktop app .
Then I make the desktop app

**Comment by bennymeg** [comment]
Hi,
Currently, I do not support nested projects.
All the projects should be inside the apps folder.
