### ISSUE TITLE
Add support for nx 13

### ISSUE THREAD

**Issue by naej56** [bennymeg/nx-electron#120]
Hi, first of all thanks a lot for the great lib.

I use nx 13.0.2 for a new project and it seem that it's not compatible.
I have many errors when i want use nx-electron with it.

I use this command to serve new electron app :  `nx run <my_app>:serve`
and get following error : 

```
 ERROR  As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this.
```

I run `nx format` and try again, but a new error show up : 
```
Cannot find module '@nrwl/workspace/src/utils/buildable-libs-utils'
Require stack:
- D:\dev\fsmm\fsms\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- D:\dev\fsmm\fsms\node_modules\@angular-devkit\architect\node\index.js
- D:\dev\fsmm\fsms\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- D:\dev\fsmm\fsms\node_modules\@nrwl\tao\src\commands\run.js
- D:\dev\fsmm\fsms\node_modules\@nrwl\tao\index.js
- D:\dev\fsmm\fsms\node_modules\@nrwl\cli\lib\run-cli.js
```

Here my NX report :
```
nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.18.1
  OS   : win32 x64
  npm  : 6.14.15

  nx : Not Found
  @nrwl/angular : 13.0.2
  @nrwl/cli : 13.0.2
  @nrwl/cypress : 13.0.2
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : 13.0.2
  @nrwl/next : Not Found
  @nrwl/node : 13.0.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : 13.0.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by naej56** [comment]
Hi,
thank's for the answer.

I'm new to nx and i don't have many skill to help you.
If i can find time, i will try.

**Comment by johnjcool** [comment]
we also need v13 support. how can we help? can you give some hints in the right direction?

**Comment by anatoliykot** [comment]
We need v13 support 😊 🙏

**Comment by bennymeg** [comment]
It seems that between v11 and v12 nx undergone a major change.
I will try to allocate time next week to re-scaffold the plugin as the new architecture.
from there, the path to v13 will be much easier.

**Comment by patrickmichalina** [comment]
Thank you!

**Comment by westhechiang** [comment]
@bennymeg I'd love to help out as our team is using NX13 and would love to see nx-electron become compatible!

**Comment by bennymeg** [comment]
@westhechiang first of all, thanks.
I have started migrating the project to version 12 on the __v12__ branch (27f786feeb3d35e4d4f09d7f13f649a6e9d31304).

One of the issues of writing a plugin to 'nx' is that it used to be coupled to angular-devkit.
It seems that on v12 nrwl de-coupled angular-devkit with their new `@nrwl/devkit` package.
I have tracked the commit that describes the bulk of the transition: 
https://github.com/nrwl/nx/commit/d4629be208d247294c345932bdccd6851c118f38#diff-ecd890d6e70978af43b465e02f3b585a7de7bfb80c39d5b8b4786e0935328e00.
I don't think that taking the same route is mandatory for the plugin to work correctly, but it will make future development easier.
If you want to take a look at it and apply similar changes to this project I would appreciate it.

In the mean time I will continue v12 development as is.

**Comment by bennymeg** [comment]
Looks like that migration was mandatory and extremely involved. I took care of it.
I've release an alpha version for v12, You can play with it if you wish.
Let me know if everything work well for you.

**Comment by anatoliykot** [comment]
@bennymeg Hey, I have tried v12 and got this error
```
Error: Unable to resolve nx-electron:execute.
The "nx-electron" package does not support Nx executors.
```

**Comment by bennymeg** [comment]
hmm, wierd.
- What version of nx are you using?
- Did you migrated your project with ng/nx update or created a new one?
- Do you use executers or builders in you nx / angular.json configuration file?

**Comment by anatoliykot** [comment]
Hey @bennymeg, thanks for your response
1. nx v12.10
2. Migrated from v11
3. (I'm using react) in workspace.json ->
<img width="469" alt="Снимок экрана 2021-11-30 в 10 27 44" src="https://user-images.githubusercontent.com/5163563/144004215-a5c08adf-18df-45ca-8dc0-d4a53568f1b4.png">

**Comment by bennymeg** [comment]
Maybe executors are supported from v13 onwards, I will try to figure it out later.
For now you can replace "executor" with "builder", there is no advantage invoking one over the other since internally I implemented everything with the new nx devkit and added compatibility adapters for angular devkit.

**Comment by johngrimsey** [comment]
Thanks @bennymeg for your work on this 🙏

**Comment by johngrimsey** [comment]
Hey @bennymeg, I'm on Nx 13, updated from 12, `nx-electron` now using `^12.0.0-alpha.6`, with Angular 13.

I've also using the per-project, and I've run `nx g @nrwl/workspace:convert-to-nx-project --all` to migrate to this.

I changed the electron application's `project.json`:

```
...
  "targets": {
    "build": {
      "executor": "nx-electron:build",
...

    "serve": {
      "executor": "nx-electron:execute",
...
```

Getting an error at the moment when I try to build/serve my electron app. Hope this output is useful:

```
> nx run electron-app:serve --verbose
Cannot find module '@nrwl/workspace/src/utilities/run-webpack'
Require stack:
- /site/node_modules/nx-electron/src/executors/build/executor.js
- /site/node_modules/@nrwl/tao/src/shared/workspace.js
- /site/node_modules/@nrwl/tao/src/commands/run.js
- /site/node_modules/@nrwl/tao/index.js
- /site/node_modules/@nrwl/cli/lib/run-cli.js
Error: Cannot find module '@nrwl/workspace/src/utilities/run-webpack'
Require stack:
- /site/node_modules/nx-electron/src/executors/build/executor.js
- /site/node_modules/@nrwl/tao/src/shared/workspace.js
- /site/node_modules/@nrwl/tao/src/commands/run.js
- /site/node_modules/@nrwl/tao/index.js
- /site/node_modules/@nrwl/cli/lib/run-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/site/node_modules/nx-electron/src/executors/build/executor.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)

```

Thanks again

**Comment by octadecimal** [comment]
I'm having the same issue as @johngrimsey with Nx13 (which I know is still being worked on). 

I'm not very familiar with Nx plugin development, but was able to get serving working with a few small changes. There are some issues (typings) but hopefully this is at least of some help to anyone looking for a quick stop-gap solution and hopefully of use to Benny as he continues to add support for 12 and 13.

https://github.com/octadecimal/nx-electron/commit/64d7cabe21933ede05c0f0071059b665517828f3

And because nx-electron is still installing webpack4, I am instead resolving webpack5 in my workspace's `project.json` via:

```json
"resolutions": {
  "nx-electron/webpack": "5.65.0"
},
```

**Comment by bennymeg** [comment]
@johngrimsey I most say, `nx-electron` versions adheres to the semantic versioning schema and designed to be used with it's corresponding major version of `angular` / `nx` (i.e nx-electron@12 compatible with angular/nx@12).

@octadecimal thanks for the patch.

A quick update: 
Since nx / angular v12 support webpack v5 but do not require it I was trying to to stick with webpack v4 for nx-electron v12 to make the update easier to whom how would like to stay with their current project configuration. Unfortunately, I could not make them to play nice with each other, so I have migrated to webpack v5 in `alpha.7`. Which means that it might work with nx v13 as well (but, as I said about, this behavior is not supported).

**Comment by johngrimsey** [comment]
Thanks @bennymeg  - appreciate I'm marching ahead with versions here. Thanks so much for `alpha.7` that is working for me 🙏

**Comment by octadecimal** [comment]
Hi @bennymeg, `alpha.7` is working for me on Nx 13.3.6 sans one minor change due to this recent commit: https://github.com/nrwl/nx/commit/e57cef09014b1732ef3c8b2c383432bba963087b

The fix for this was to simply update the imports of `readJsonFile` and `writeJsonFile` to import from `@nrwl/devkit` in `utils/generate-package-json.ts`.

[patch](https://gist.github.com/octadecimal/a6c93154e6e1dc867ba74ad26135df69)

I'm still unable to scaffold a new project out of the box, but being able to serve has been sufficient for now. Thanks as always -- and happy holidays!

**Comment by bennymeg** [comment]
Thanks,
If that change is compatible with v12 I will update it.

**Comment by mwoodpatrick** [comment]
Any update on getting this plugin to work with Nx 13 I'm very interested in this and possibly helping out in some way. Very interested in using this plugin with react/remix

**Comment by bennymeg** [comment]
@mwoodpatrick Thanks,
There are still couple of minor bugs in v12 beta. Once it will be stable, I will begin v13 development.
I believe this will be a much smoother transition so I should make it quick. But if not, I would let you know.

**Comment by WarKaa** [comment]
Hi, I am interested in using this plugin with Nx 13
Any update on how it is going ?

**Comment by bennymeg** [comment]
I have just released **v12** 🎉.
I will release an alpha for v13 in the next couple of weeks.

**Comment by WarKaa** [comment]
Great news, thanks you for your work @bennymeg

**Comment by reutopiaer** [comment]
at v13 just run:npm i -D @nrwl/workspace@12.10.0,serve can up.
it's a tmp fix,waiting for alpha for v13.

**Comment by Luca8991** [comment]
> at v13 just run:npm i -D @nrwl/workspace@12.10.0,serve can up.
> it's a tmp fix,waiting for alpha for v13.

@reutopiaer unfortunately it's not working for me, as it throws me this error when building an imported Nx library:
```
Invalid source or target versions. Source: 4.0, Target: 5.0.

Only backwards compatibility between "5.0" and "4.0" is supported.
This error can be caused by "@nrwl/..." packages getting out of sync or outdated project graph cache.
Check the versions running "nx report" and/or remove your "nxdeps.json" file (in node_modules/.cache/nx folder).
```

**Comment by bennymeg** [comment]
Alpha version for v13 had been released.
Currently, generating per project 'package.json' file is not working, to build the project add `--generatePackageJson=false` argument. 
If someone have an idea why it is failing, please let me know.

**Comment by yorublaireau** [comment]
Just starting a new project with NX 13, using your alpha release.
Starting from a blank NX, I've added a react project, then ran: 
```
npm install -D nx-electron@13.0.0-alpha.0
npx nx g nx-electron:app app-electron --frontendProject=app-react
```
And I get the following error:
```
Cannot find module '@angular-devkit/core'
Require stack:
- ...\project\node_modules\nx\src\commands\ngcli-adapter.js
- ...\project\node_modules\nx\src\commands\generate.js
- ...\project\node_modules\nx\src\cli\index.js
- ...\project\node_modules\nx\src\cli\init-local.js
```
Since you seem to have migrated away from this, I thought I'd let you know.

As a work around, I've installed `@angular-devkit/core` and `@angular-devkit/schematics` as dev dependencies and it seems to work now.

**Comment by kyleryanbanks** [comment]
I didn't notice the ng12 limitation while I was spinning up a new app tonight.

It looks like the read/write functions have shifted

In generate-package-json.js it imports some utils that seem to have moved.

I was able to get electron running against by updating the import.

//const fileutils_1 = require("@nrwl/workspace/src/utilities/fileutils");
const fileutils_1 = require("@nrwl/devkit");

This is with the standard nx setup at the current versions
"dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@nrwl/angular": "13.10.3",
    "rxjs": "~7.4.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.0",
    "@angular-eslint/eslint-plugin": "~13.1.0",
    "@angular-eslint/eslint-plugin-template": "~13.1.0",
    "@angular-eslint/template-parser": "~13.1.0",
    "@angular/cli": "~13.3.0",
    "@angular/compiler-cli": "~13.3.0",
    "@angular/language-service": "~13.3.0",
    "@nrwl/cli": "13.10.3",
    "@nrwl/cypress": "13.10.3",
    "@nrwl/eslint-plugin-nx": "13.10.3",
    "@nrwl/jest": "13.10.3",
    "@nrwl/linter": "13.10.3",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "13.10.3",
    "@types/jest": "27.0.2",
    "@types/node": "16.11.7",
    "@typescript-eslint/eslint-plugin": "~5.18.0",
    "@typescript-eslint/parser": "~5.18.0",
    "cypress": "^9.1.0",
    "electron": "^17.0.0",
    "eslint": "~8.12.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "exitzero": "^1.0.1",
    "jest": "27.2.3",
    "jest-preset-angular": "11.1.1",
    "nx": "13.10.3",
    "nx-electron": "^12.1.0",
    "prettier": "^2.5.1",
    "ts-jest": "27.0.5",
    "typescript": "~4.6.2"
  }

**Comment by patrickmichalina** [comment]
Make that nx 14 😅

**Comment by bennymeg** [comment]
@kyleryanbanks I think you are missing @nrwl/angular dependency. It should include the appropriate devkit. For now I have added the devkit to the beta (even due it is require by nx and not this plugin).

**Comment by bennymeg** [comment]
[v13.0.0](https://www.npmjs.com/package/nx-electron/v/13.0.0) Published 🎉
