### ISSUE TITLE
preload.js not being packaged

### ISSUE THREAD

**Issue by EchopixUser** [bennymeg/nx-electron#121]
https://github.com/bennymeg/nx-electron/blob/16f9b9ded8bf95790677cc99aff5fa7ba1b79845/src/builders/package/package.impl.ts#L141

Hello,
my preload.ts is compiled and built into preload.js, however when running the **make** command it does not get bundled in the asar. I've tracked it down to this line, if I revert it to `filter: ['main.js', 'preload.js', 'assets']` without the regex, it works and bundles it correctly.

**Comment by bennymeg** [comment]
That's probably broken because I wrote regex instead of glob pattern. 🙄
I'll fix it.
