### ISSUE TITLE
Donation support

### ISSUE THREAD

**Issue by octadecimal** [bennymeg/nx-electron#123]
Hey Benny -- I'm of the group excitedly awaiting support for Nx 13. Unfortunately, I am also woefully unskilled in the black arts of creating Nx plugins and am therefore unable to contribute to the efforts as much as I'd like to.

Looking at the issue for adding Nx 13 support, I can see I am not alone in greatly appreciating the library you've created as well as the work you continue to put into it. 

I kindly encourage you to add a mechanism for us to donate as a token of our thanks. Even if you don't need it, I would love to, at least, buy you a beer/coffee for the great plugin you've created and maintain!

**Comment by bennymeg** [comment]
Hi,
Thank you for the kind words.
Unfortunately, currently I do not qualify for the Github's sponsor program, maybe in the future I will be able to join the program.

**Comment by octadecimal** [comment]
Understood. Will close this as to not create clutter -- many thanks again for all your work!
