### ISSUE TITLE
Doesn't recognize alternative front-end project's output dist

### ISSUE THREAD

**Issue by pillsilly** [bennymeg/nx-electron#126]
**Describe the bug**

**To Reproduce**
1. Go to 'angular.json'
2. Change your front end projects `outputPath` to a new path
3. build your front end project
4. perform npx nx package yourElectronApp
5. the front end project's dist is not copied to resource dir (NOK)

**Expected behavior**
`nx package` should deduce the real `outputPath` if user has defined it. not to always assume that it's default (dist/app/appName)

**Comment by bennymeg** [comment]
nx-electron relays on the compiled files tree structure.
I do not think there is an easy fix to make this change work.
I think for now it best to stick to the default destinations (unless you have a solution for this).
