### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by zodiac1214** [bennymeg/nx-electron#127]
Hi @bennymeg , i have been using this project for two of my apps now and i really appreciate what you have done. My app is doing fairly well because of open source project like this. Would you be able put a donation page? i'd like to contribute :)

**Comment by bennymeg** [comment]
Hi,
Sorry for the late response.

First of all, Thank you! Really!
Unfortunately, I do not qualify for `Github sponsors` yet.
It seems that the open collective is the way to go but I am not very familiar about this subject. I will investigate about them when I would have more time (and at least after I will release v12 and start working on v13).

**Comment by bennymeg** [comment]
💖 We've been approved for [GitHub sponsors](https://github.com/sponsors/bennymeg) 🎉 (#123).

**Comment by zodiac1214** [comment]
Done! As promised almost a year ago

**Comment by bennymeg** [comment]
Thank you!
