### ISSUE TITLE
v12 beta cant generate

### ISSUE THREAD

**Issue by Gerolmed** [bennymeg/nx-electron#128]
When generating an electron project (nx-electron@12.0.0-beta.0) for a nx 12.10 workspace I get an error.
```
$ nx g nx-electron:app launcher --frontendProject=frontend-store
√ In which directory should the electron application be generated? · 
Package "nx-electron" was found but does not support schematics.
```

**Comment by bennymeg** [comment]
Thanks,
I will try to reproduce and fix it if needed.

**Comment by Gerolmed** [comment]
Did the commit fix it? How can I try it out as it doesnt seem to be pushed to npm

**Comment by bennymeg** [comment]
Yes, but I want to test it a bit more. I'm not sure that is the way to solve it.

**Comment by bennymeg** [comment]
@Gerolmed I've published the fix (_beta.2_).

**Comment by Gerolmed** [comment]
Great that seems to have fixed it for the generation part. My webpack config seems to require me to create a "src/assets/.gitinclude" but other than that I can serve the app.

Though I did notice there is an issue with make and package, but I might make a new issue for that
