### ISSUE TITLE
[Question] How to create multi platform builds?

### ISSUE THREAD

**Issue by julianpoemp** [bennymeg/nx-electron#129]
I don't understand how to build the electron app to binaries for multi platforms. I'm using MacOS 11.6.2 and I would like to build a binary for windows and linux, too.

How can I do this using nx-electron and Angular?

**Comment by naej56** [comment]
Hi @julianpoemp,

I think you meen packing your application.

You have two choices for that :

1) use option `--plateform` in your packing command.

Exemple for windows and linux packing : 
`nx run <electron-app-name>:package --plateform=windows,linux`
You can find all option on [this page](https://github.com/bennymeg/nx-electron/blob/master/src/builders/package/schema.json)

2) use static packing configuration.

You can find exemple on [this page](https://github.com/bennymeg/nx-electron/blob/master/docs/packaging.md)
You can find all options and détails on [Electron Builder documentation](https://www.electron.build/configuration/configuration)
**Notice** : Static configuration will overide the options you pass manually via the command line or choose via the angular console.

Hope this can help you.

**Comment by julianpoemp** [comment]
Hi @naej56,

thank you for your fast answer 😄 

I tried it using `--platform` but it doesn't work. It still builds only the MacOS version.

I tried two different ways to pass the `platform`argument:

1. In the build command:
    
     nx run <electron-app>:package --platform=windows
     
2. After that hadn't worked I tried to append it in the angular.json file:

````json
       ...
        "package": {
          "builder": "nx-electron:package",
          "options": {
            "platform": "windows",
            "name": "citarlo-desktop",
            "frontendProject": "citarlo-web",
            "outputPath": "dist/packages",
            "prepackageOnly": true
          }
        },
        ...
````

Both didn't work...

**Comment by naej56** [comment]
i have no way to test right now sorry.

But may be you could try with a config file `.\apps\<electron-app-name>\src\app\options\maker.options.json`

**Comment by bennymeg** [comment]
@julianpoemp multiplatform builds are not a trivial thing, especially on mac.

You will need to compile the program with the target machine instructions set.
Which means you will probably need to invoke the packager inside a _docker container/virtual machine/build server_ that runs your target platform.

You can find detailed explanation on [this](https://www.electron.build/multi-platform-build.html) document.

**Comment by julianpoemp** [comment]
I got it working with nx-electron. I had to install a 64bit version of wine on MacOS BigSur. Because `--platform` falls to default while using `prepackageOnly=true` I set it to `false` for all platforms. I don't understand why, but it works. Further more I had to set the base-href attribute to "./". I can now build binaries for macOS, Windows and Linux on the same computer.

Thank you for your help! 😃

**Comment by bennymeg** [comment]
I didn't knew Wine is an option one can use, nice.
You should use the following command instead:
```sh
nx build <frontend-app> --prod --base-href='./' && nx build <electron-app> --prod && nx run <electron-app>:make --platform=windows
```

**Comment by tmtron** [comment]
> nx build <frontend-app> --prod --base-href='./' && nx build <electron-app> --prod && nx run <electron-app>:make --platform=windows

@bennymeg where does the `platform` parameter come from? 
* according to the [readme "Making Nx Electron Application"](https://github.com/bennymeg/nx-electron#making-nx-electron-application) it should be in [validation/maker.schema.json](https://github.com/bennymeg/nx-electron/blob/master/packages/nx-electron/src/validation/maker.schema.json)
  * But I guess it is [executors/package/schema.json](https://github.com/bennymeg/nx-electron/blob/master/packages/nx-electron/src/executors/package/schema.json)
  * maybe the link in the readme is wrong? i.e. it is the same link as for [Packaging Nx Electron Application](https://github.com/bennymeg/nx-electron#packaging-nx-electron-application)
* also [electron-builder cli](https://www.electron.build/cli) does not have a platform argument

**Comment by bennymeg** [comment]
All the executors have a schematic file (which is where the platform option comes from).
The package executor have an additional schematic for the builder options.

I do not use the CLI, I use the API (which is poorly documented), you can find more information about the platform variable inside `electron-builder` source files. ([Platform](https://github.com/electron-userland/electron-builder/blob/7f933d0004a0a5f808a2a1c71dca7362cab2728e/packages/app-builder-lib/src/core.ts#L21-L30), [createTargets](https://github.com/electron-userland/electron-builder/blob/5b4305ec336cf6f5866a26cde7fe99f18d7ac566/packages/electron-builder/src/builder.ts#L195-L208)).

**Comment by bennymeg** [comment]
Correct
