### ISSUE TITLE
electronZipDir not valid

### ISSUE THREAD

**Issue by gespina** [bennymeg/nx-electron#13]
In the readme there is an option to specify "electronZipDir" but when I try to add it to packager.option.json I get an error.  Is this option available?

**Comment by bennymeg** [comment]
Hi,
This is a [recent](https://github.com/electron/electron-packager/blob/master/NEWS.md#1420---2020-01-13) new feature. 

I will add it to the next release.

**Comment by bennymeg** [comment]
Added!
