### ISSUE TITLE
Error running the electron application

### ISSUE THREAD

**Issue by oussamarouabah** [bennymeg/nx-electron#133]
**Steps to reproduce the behavior:**
1. Create the nx workspace `npx create-nx-workspace@latest`
2. Add the necessary plugins 
     1. `npm i -D @nrwl/react`
     2. `npm i -D nx-electron`
3. Create apps
     1. `ng g @nrwl/react:application`
     2. `nx g nx-electron:application` 
4. Run the application using this command `nx run-many --target=serve --projects=school,school-desk --parallel`

**Expected behavior**
Run the desktop app

**System :**
 - OS: `fedora 35`
 - Nx Electron Version (nx = `13.4.5`, nx-electron=`11.4.1` )
 - Node version `v14.17.6`

** Error **
Trying to run the electron app using this command `nx run-many --target=serve --projects=school,school-desk --parallel` and got the following error.

nx run-many --target=serve --projects=school,school-desk --parallel

>  NX  Running target serve for 2 project(s):

  - school
  - school-desk

———————————————————————————————————————————————

> nx run school:serve 

> nx run school-desk:serve 
Cannot find module '@nrwl/workspace/src/utils/buildable-libs-utils'
Require stack:
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/nx-electron/src/builders/build/build.impl.js
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/@angular-devkit/architect/node/index.js
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/@nrwl/tao/src/commands/ngcli-adapter.js
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/@nrwl/tao/src/commands/run.js
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/@nrwl/tao/index.js
- /home/oussama/workspace/work/softbrew/school/softbrew/node_modules/@nrwl/cli/lib/run-cli.js
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:4200/, http://127.0.0.1:4200/
<i> [webpack-dev-server] 404s will fallback to '/index.html'

>  NX  Web Development Server is listening at http://localhost:4200/

Entrypoint main [big] 1.62 MiB (1.89 MiB) = runtime.js 50 KiB vendor.js 1.51 MiB main.js 61.8 KiB 3 auxiliary assets
Entrypoint polyfills [big] 746 KiB (907 KiB) = runtime.js 50 KiB polyfills.js 696 KiB 2 auxiliary assets
Entrypoint styles [big] 430 KiB (534 KiB) = runtime.js 50 KiB styles.css 399 bytes styles.js 380 KiB 2 auxiliary assets
chunk (runtime: runtime) main.js (main) 52.3 KiB [initial] [rendered]
chunk (runtime: runtime) polyfills.js (polyfills) 651 KiB [initial] [rendered]
chunk (runtime: runtime) runtime.js (runtime) 33.7 KiB [entry] [rendered]
chunk (runtime: runtime) styles.css, styles.js (styles) 363 KiB (javascript) 398 bytes (css/mini-extract) [initial] [rendered]
chunk (runtime: runtime) vendor.js (vendor) (id hint: vendor) 1.48 MiB [initial] [rendered] split chunk (cache group: vendor) (name: vendor)
webpack compiled successfully (af40565a0bcb454e)
No issues found.

**Comment by bennymeg** [comment]
Miss-matched versions.
Please use nx@11 with nx-electron@11.
