### ISSUE TITLE
12 beta cant make or package

### ISSUE THREAD

**Issue by Gerolmed** [bennymeg/nx-electron#135]
**Describe the bug**
When running both package or make it complains about this:
```
 ERROR  Executor "nx-electron:package" should return either a Promise or an AsyncIterator
```

Im using `beta.3` and nx `12.10.1`

**Comment by bennymeg** [comment]
I don't understand from that came from, but I've fixed it.
Kindly verify that everything works properly for you as well.

**Comment by Gerolmed** [comment]
Seems to be building now, but the app isnt actually running properly. (Not even the electron code)

The image below shows the two windows (left == dev, right == exe). At least the electron code hiding the top bar should be working right?

Is there a way to see the logs? Ive tried starting to run the exe via console, but its not logging anything.

![image](https://user-images.githubusercontent.com/19486712/151640185-cb548a88-79a3-4fb9-bd6f-04a2ef44fc6b.png)

**Comment by bennymeg** [comment]
Everything works fine on my end.
Activate the developer tools window `mainWindow.webContents.openDevTools();` and check out the logs.

**Comment by Gerolmed** [comment]
It seems that it can't find the files. Im also using Vue https://github.com/ZachJW34/nx-plus/tree/master/libs/vue which might be the issue.
![image](https://user-images.githubusercontent.com/19486712/151802256-fe689b28-260f-47c0-820d-fd992c5f5079.png)

**Comment by Gerolmed** [comment]
Nvm Im quite stupid forgot changing the base ref on build. Now its working :D
Thanks a lot
