### ISSUE TITLE
Cannot Find Module within Electron App

### ISSUE THREAD

**Issue by lookapanda** [bennymeg/nx-electron#14]
**Describe the bug**
If you create a lib using `nx g @nrwl/workspace:lib name` the created library cannot be imported within the Electron app as it fails to resolve.

**To Reproduce**
1. Create Electron App in Nx
2. Create Library in Nx
3. Try to import it like `@workspace/libName`

**Expected behavior**
It should resolve

**Desktop (please complete the following information):**
 - WSL 2 Ubuntu 18.04
 - 9.0.0-beta.2

**Comment by lookapanda** [comment]
Okay, I looked into it and it is because the `tsconfig.json` of the electron app has its own `paths` property.

A workaround is to put the contents of it to the root `tsconfig.json`:

```
"@benny/nx-electron/schema/packager": [
        "node_modules/nx-electron/src/validation/packager.schema.json"
      ],
      "@benny/nx-electron/schema/maker": [
        "node_modules/nx-electron/src/validation/maker.schema.json"
      ]
```

**Comment by bennymeg** [comment]
Thank you, Ill take a look.

I actually tried to simplify the paths to the json schema's with no luck, I will try to fix it as well.
