### ISSUE TITLE
file_utils1.writeJsonFile is not a function

### ISSUE THREAD

**Issue by markscarna** [bennymeg/nx-electron#142]
When I am trying to build the electron app, I get `file_utils1.writeJsonFile is not a function`. This is fixed when I replace the old `@nrwl/workspace` library with the new `@nrwl/devkit` library. You can see that at [this pull request.](https://github.com/bennymeg/nx-electron/pull/141)

**Comment by eglove** [comment]
Same here, thanks for the update.

**Comment by orestisioakeimidis** [comment]
I have the same issue! Please fix!

**Comment by bennymeg** [comment]
Use nx v12 with nx-electron v12 in your project.

**Comment by orestisioakeimidis** [comment]
Hey @bennymeg, thanks for the response. Don't get me wrong here, I didn't want to put any pressure on this. The "Please fix!" part might've created the wrong impression, I have to admit.

I am already using v12 for both and it works great, thanks for all the effort you put into this project. The reason I need this is that I'd like to update all dependencies to 13, including Angular 13, NX etc.

Nevertheless, keep up the great work and let me know if you need anything at all, on adding support for Nx13. Cheers!
