### ISSUE TITLE
Consider removing TSLint

### ISSUE THREAD

**Issue by lookapanda** [bennymeg/nx-electron#15]
Not a bug report, but I was wondering why TSLint gets included with this package.

If you create an Electron app, I found a `tslint.json` and also got some linting errors regarding tslint. But nx is already using eslint.

**Comment by bennymeg** [comment]
When you create your electron project you can choose which linter to use, ESlint or TSlint (default).
I assume that is the case with nx as well, I didn't try to mix them up, but you should use the same one for both.

Ill take a look.

**Comment by lookapanda** [comment]
It didn't ask me which linter I wanted to use

**Comment by bennymeg** [comment]
It did not asks, you have to choose either by selecting it from the drop down list (nx-console) or by adding the linter option `--linter=eslint`.

![image](https://user-images.githubusercontent.com/25218142/77829495-89f49600-7133-11ea-8a5f-651d8fe097e4.png)

**Comment by lookapanda** [comment]
Well, by default nx uses eslint, I just followed their "Getting Started" tutorial and created a basic workspace. I will try the CLI flag

**Comment by bennymeg** [comment]
Your right, updated eslint to be the default linter.

**Comment by lookapanda** [comment]
Great, thank you! :D
