### ISSUE TITLE
Missing `makerOptionsPath` package option

### ISSUE THREAD

**Issue by jupapios** [bennymeg/nx-electron#151]
**Describe the bug**

It seems the option to override the maker options was removed, this is commit https://github.com/bennymeg/nx-electron/commit/adb8bb9567fafda4d949d9c588f6c05fc1884d45 that originally added support to that option. It is also listed in the changelog https://github.com/bennymeg/nx-electron/blob/master/CHANGELOG.md#features but when you try to use it it doesn't exist which can be confirmed in the code from `master`.

**To Reproduce**
- Modify the `makerOptionsPath` option to use a different file (remove the default one)
- You see this error `Error: ENOENT: no such file or directory, stat '.../apps/desktop-shell/src/app/options/maker.options.json'`

**Expected behavior**
It should use the maker options path you defined

The `makerOptionsPath` option was supported in pre 12.0.0 versions of `nx-electron`, I'm using it in a project that uses `nx-electron@11.4.1` and it works just as expected, it seems to have been remove in `12.x.x`

**Desktop (please complete the following information):**
 - OS: OSx
 - Nx Electron Version 12.10.0

**Comment by bennymeg** [comment]
Thanks for letting me know,
I will check it out.
