### ISSUE TITLE
Multiple Frontend Projects

### ISSUE THREAD

**Issue by ratatoeskr666** [bennymeg/nx-electron#154]
Currently there is no possibility to provide multiple frontend projects for multi window applications that use different frontend projects for each window.

It would be wonderful if "frontendProject" in the angular.json nx builder config could also be an array.

My workaround is currently to disable asar and copy&paste the built frontend project to the resource folder.

**Comment by bennymeg** [comment]
Thank you for the suggestion. I would must definitely would like to include this feature, but as of now I do not have mush time to implement it.

**Comment by paustint** [comment]
I have this same use-case +1

**Comment by bennymeg** [comment]
Added on v14!
