### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by dhrn** [bennymeg/nx-electron#157]
**Is your feature request related to a problem? Please describe.**
It is difficult to work with the repo, a lot options are not having the docs. please if possible add some docs to work with the repo.

(couldn't run the code base in the Linux machine)

**Describe the solution you'd like**
please include an example app and possible override options. May be host the docs in the github pages

**Comment by bennymeg** [comment]
The packager side is well documented [here](https://www.electron.build/).

The Nx options side could be viewed by appending `--help` to each command, it will state and explain all the available options for the requested command (as stated in the docs). For ease of use, I recommand using the [nx-console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) plugin, it will make using the plugin intuitively.

All the rest (including this explanation) is documents under the repo docs.
