### ISSUE TITLE
Auto deploy to GitHub after making

### ISSUE THREAD

**Issue by TomTomB** [bennymeg/nx-electron#16]
**Describe the bug**
Running `nx run test-app:make` doesnt deploy the packaged nsis to GitHub.

This is my current `maker.options.json` file:

```
{
  "$schema": "../../../../../node_modules/nx-electron/src/validation/maker.schema.json",
  "productName": "Test App",
  "asar": true,
  "publish": [
    {
      "provider": "github",
      "owner": "TomTomB",
      "repo": "test-stuff"
    }
  ],
  "win": {
    "target": ["nsis"]
  }
}
```

The electron-builder output:
```
• electron-builder  version=22.4.1 os=10.0.18363                                                                       
• writing effective config  file=dist\executables\builder-effective-config.yaml         
• packaging       platform=win32 arch=x64 electron=7.2.1 appOutDir=dist\executables\win-unpacked              
• asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available                                                                                          • default Electron icon is used  reason=application icon is not set                                                     
• building        target=nsis file=dist\executables\Test App Setup 0.0.0.exe archs=x64 oneClick=true perMachine=false
• building block map  blockMapFile=dist\executables\Test App Setup 0.0.0.exe.blockmap      
```

Am I missing something?

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Nx Electron Version: 9.0.0-beta.2

**Comment by bennymeg** [comment]
it seems that electron builder did not attempt to publish your app.
what is the configuration you use to [publish](https://www.electron.build/configuration/publish) a regular electron app? is it the same?

**Comment by TomTomB** [comment]
Its exactly the same. It seems like only some parts of the config file are used. E.g. setting asar to true does nothing aswell. There is a warning for that inside the electron builder output.

**Comment by bennymeg** [comment]
asar, targets, arch parameters are overridden by the cli.
try `nx run test-app:make --asar --publish always`

**Comment by bennymeg** [comment]
@TomTomB it appears I had a bug handling the publish parameter.
If you still have the issue, please take a look at #23
