### ISSUE TITLE
Error when installing in nx v14 workspace

### ISSUE THREAD

**Issue by wangzishi** [bennymeg/nx-electron#162]
**Describe the bug**
Error when installing in nx v14 workspace.

**To Reproduce**
1. Install nx-electron in a nx v14 workspace.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8288105/167340672-bc09d746-9d98-4bdf-92ec-4098070a8f9c.png)

**Comment by bennymeg** [comment]
v13 is compatibly with v13 only.
