### ISSUE TITLE
`nx g nx-electron:app` is looking for an angular.json configuration file in a react project

### ISSUE THREAD

**Issue by ainvoner** [bennymeg/nx-electron#166]
**Describe the bug**
`nx g nx-electron:app <electron-app-name> --frontendProject=<frontend-app-name>` command is looking for a configuration in  /angular.json file while running in a nx/react project configuration.

**To Reproduce**
follow README instructions in a clean project:
1. run `npx create-nx-workspace@13`
 - choose a react project with emotion styles
2. run `npm install -D nx-electron`
3. run`nx g nx-electron:app <electron-app-name> --frontendProject=<frontend-app-name>`
 - this will result an error which already defined here [issue 146](https://github.com/bennymeg/nx-electron/issues/146)
 - issue resolved after adding those missing modules
 - once fixing the above issues a new error is prompt:
 `Error: Cannot find configuration for 'app-client' in /angular.json.
    at readProjectConfiguration (/Users/me/Documents/GitHub/my-project/node_modules/nx/src/generators/utils/project-configuration.js:154:15)
    at addProxy (/Users/me/Documents/GitHub/my-project/node_modules/nx-electron/src/generators/nx-electron/generator.js:100:65)
    at /Users/me/Documents/GitHub/my-project/node_modules/nx-electron/src/generators/nx-electron/generator.js:168:13
    at Generator.next (<anonymous>)
    at fulfilled (/Users/me/Documents/GitHub/my-project/node_modules/tslib/tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Cannot find configuration for 'app-client' in /angular.json.`

**Expected behavior**
project configuration should be found in my-app/project.json and not in  my-app/angular.json file

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Nx Electron Version 13.1.0

**Additional context**
Thanks!!!

**Comment by bennymeg** [comment]
Thank you for the elaborate report.

- I thought issue 146 was fixed, did you remember if the requested packages was installed when the error appeared?
- readProjectConfiguration() is part of the nx devkit, so I suspect it might be an issue with nx.
  could you try creating an @nrwl/node app and see if the error exist as well?

**Comment by bennymeg** [comment]
Fixed the first issue on `v13.1.1`.

**Comment by bhuntay** [comment]
had to install `@angular-devkit/core` and `@angular-devkit/schematics` on `nx-electron@14.0.2` to make it work with my react application
