### ISSUE TITLE
Upgrade to nx@14

### ISSUE THREAD

**Issue by r-hannuschka** [bennymeg/nx-electron#168]
**Is your feature request related to a problem? Please describe.**
github pipeline fail with: 

```bash
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! code 1
npm ERR! path /home/runner/work/easyBSB/easyBSB/node_modules/nx-electron/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/init
npm ERR! >  NX   Cannot read properties of undefined (reading 'endsWith')

...
```

This happens for the simple reason we have installed nx@14 but nx-electron use nx@13

**Describe the solution you'd like**
upgrade deps to nx@14.x

**Describe alternatives you've considered**
As workarround what helps for now is to override inside the package.json the deps of nx-electron and it seems to work.

```json
{
  ...
  },
  "overrides": {
    ...
    "nx-electron": {
      "@nrwl/devkit": "14.1.9",
      "@nrwl/workspace": "$@nrwl/workspace"
    }
  }
}
```

**Additional context**
Fun part here, we test this on multiple local systems it was working. Because maybe npm cache or something else i do not know. It only failed inside ci pipeline and gitpod.

**Comment by lailo** [comment]
I'm still having the same problem even with the `v13.2.1` with nx `v14.1.9`.
Anyone an Idea what else could be the problem?

**Comment by r-hannuschka** [comment]
yeah was a mistake forgotton to run npm again, so it takes the wrong package-lock.json :/ What still helps is the override from above.

**Comment by orestisioakeimidis** [comment]
@lailo The problem in my case was the missing `root` property in the `project.json` files. For instance, if the `sourceRoot` is `apps/my-app/src`, you need to add the `root` property `apps/my-app`.

It works fine after adding this property. I am using version 2 of the `angular.json` file.

**Comment by Crikey-Mikey** [comment]
Has anyone had success with nx@14? Unfortunately, updating npm to v8 to make use of `overrides` is not an option for me.

**Comment by keypuncherlabs** [comment]
It's working fine for me out of the box with NX v14.

**Comment by mr-furkee** [comment]
for me it is working fine locally (even with clean installs) but was failing on github actions, so i used the following:

```yaml
steps:
  ...
  - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --ignore-scripts # added ignore scripts flag to bypass the build step
```

**Comment by lbAntoine** [comment]
The overrides solution don't work for me :'( got the same problem on my pipeline

**Comment by sngh938** [comment]
Still doesn't work, steps to reproduce

1. Using nvm to install node v16.17.0
2. Install nx using npx create-nx-workspace@latest somename (use new workspace for apps option). This creates workspace with version v14.5.8
3. run npm i -D @nrwl/react
4. run nx g @nrwl/react:app some app (installed react router and styled-components for style)
5. run nx build and nx serve to make sure the default react app works 
6. run npm install -D nx-electron, get the following error
`....
npm ERR! command failed
npm ERR! command sh -c -- node ./bin/init
npm ERR! >  NX   Cannot read properties of undefined (reading 'endsWith')

npm ERR! A complete log of this run can be found in:
...`

Seems like out of the box nx-electron is referring to nx@13.10.6

**Comment by daiky00** [comment]
did anybody found solution to this problem. I have the same issue.... but in my case the app is blank and I dont get errors

**Comment by daiky00** [comment]
Here is the image of the error.
<img width="779" alt="Screen Shot 2022-08-27 at 11 40 38 AM" src="https://user-images.githubusercontent.com/15005162/187037366-5837ae74-2658-45c3-a9a6-d1992360a2ec.png">

**Comment by daiky00** [comment]
The app looks completely blank
<img width="1318" alt="Screen Shot 2022-08-27 at 11 42 46 AM" src="https://user-images.githubusercontent.com/15005162/187037436-afd93750-e179-44b2-a0e8-489d58c4d0c3.png">

**Comment by sviatoslav-lebediev** [comment]
@daiky00 it looks like the problem is that your front-end hasn't been started, no? it says that electron can't load http://localhost:4200.

**Comment by daiky00** [comment]
@sviatoslav-lebediev  I didn't know you needed to start the frontend though? it works after started my frontend project in another terminal but that feels weird.

**Comment by sviatoslav-lebediev** [comment]
@daiky00 usually I run it in this way `nx run-many --target=serve --projects=cfl-main,cfl-renderer --parallel` but I have a few electron apps in the same repo. So I don't know if you can just run your app as `nx serve`. As for the second question - take a look at the `loadMainWindow` method. In dev mode, it will load a URL but  for the packaged version will load a bundled index.htm

**Comment by bennymeg** [comment]
Please use the discussions section for that so other people could take advantage of you conversation. The issues section should be used for bug reports only.

**Comment by sngh938** [comment]
Testing my steps on node v14.17.5, doing the same steps I posted above  still no success, npm install -D nx-electron seems to be hanging at 

...
> nx@13.10.6 postinstall /Users/srinath.n/tsc3.0/itshinni-workspace/node_modules/nx-electron/node_modules/nx
> node ./bin/init

**Comment by isaacpalka** [comment]
Experiencing the same issue, but the "overrides" solution didn't work for me. Any updates here?

**Comment by bennymeg** [comment]
@isaacpalka There is an v14-alpha version on npm.

**Comment by TheMikeSanto** [comment]
14.0.0-alpha.1 isn't packaging my front-end app, resulting in a blank window when booting the app. Any ideas on remedying this? My build works perfectly on 13.2.1.

**Comment by alljinx** [comment]
Same issue here, nx-electron works well with nx 14.5.10 but crash at post-install with nx 14.7.13...

**Comment by dhrn** [comment]
@bennymeg when can we expect v14 upgrade?

**Comment by bennymeg** [comment]
@alljinx nx-electron v13 is only compatible with nx v13? which version are you using?
@dhrn once I understand if the alpha is broken or if the problem is version mixing.

**Comment by alljinx** [comment]
@bennymeg nx-electron 13.2.1 and nx 14.5.10 seems to works like a charm in my project...

**Comment by TheMikeSanto** [comment]
@bennymeg When do you expect v14 to drop?

**Comment by dhrn** [comment]
just curious to know the progress on this @bennymeg

**Comment by bennymeg** [comment]
Released!
