### ISSUE TITLE
Electron builder configuration issues

### ISSUE THREAD

**Issue by kylebjordahl** [bennymeg/nx-electron#17]
**Describe the bug**
I am trying to set the application icon for electron builder, but electron builder continues to report that icon is not set.

**simple maker.options.json**
```json
...
  "icon": "apps/desktop-app/src/assets/fingerprint.icns",
...
```

But in reality, I believe I need a different icon to build on Mac / Win, based on other (non NX) electron builder projects, so it should be something like this:
```json
...
  "mac": {
    "icon": "apps/desktop-app/src/assets/fingerprint.icns"
  },
  "win": {
    "target": "portable",
    "icon": "apps/desktop-app/src/assets/fingerprint.ico"
  }
...
```

I have tried both, but the app icon continues to ignore these settings and only uses the default electron setting.

Overall, it seems that **most** of the settings which seem to be valid (based on the json schema provided) are ignored; the only argument that we are successfully passing is `extraResources`

**Expected behavior**
electron builder options configured in `maker.options.json` should be applied to electron builder process when running `nx run [app-name]:make`

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Nx Electron Version [e.g. 9.0.0-beta.2]

**Comment by bennymeg** [comment]
this seems correct, sometimes windows cache the icons, try restarting you PC and check again.

**Comment by kylebjordahl** [comment]
Hi @bennymeg -

I'm fairly certain it's not a caching issue; when I run the `make` command, I get this line in the builder output:
```
  • default Electron icon is used  reason=application icon is not set
```

**Comment by bennymeg** [comment]
Hi, 

That's weird, it looks like you defined it correctly, do you mind creating a new clean project with the same config file and see if it works?

Also, if you build the windows distribution on a windows machine, the icon path should look like that:
```
...
  "win": {
    "target": "portable",
    "icon": "apps\\desktop-app\\src\\assets\\fingerprint.ico"
  }
...
```

Regarding the other issue, by design some of the parameters get override in certain situations, can you give me a list of settings that dues not work for you?

**Comment by kylebjordahl** [comment]
Ok, I think I've sorted the icon thing, but it leads to a particular setting that doesn't work: directories. I realized that I hadn't configured the `buildResources` directory yet, so my icon paths are defaulting to `build/...`

**But**, after configuring `directories:{ buildResources: ... } `it still didn't find my icons, so it seems that at least `buildResources` doesn't get merged properly.

So, *for anyone else running into this issue*, I have just moved my assets to a root level `build` directory, which doesn't exactly jive with NX conventions per-se, but it works for now.

Also, I've only got a macOS environment to build in, but duly noted on the path format, thanks!

**Comment by bennymeg** [comment]
> But, after configuring directories:{ buildResources: ... } it still didn't find my icons, so it seems that at least buildResources doesn't get merged properly.

Yes, in order for the package to work correctly I have to define the electron package structure, so it override your directories setting.
I currently trying to find a way to enable partial control for that setting.

> I have just moved my assets to a root level build directory, which doesn't exactly jive with NX conventions per-se, but it works for now.

Could you please explain? what is the convention in NX for build resources?

**Comment by kylebjordahl** [comment]
I'm not exactly sure what the convention is, but it seems that it would be somehow nested inside the `app/[app name]` folder, much like individual tsconfig files.

In the end, another person on our team was able to make it work by not specifying the `buildResources` directory and just specifying the absolute path in the repo. 

Perhaps, since you need to define the electron package structure already, the `buildResources` property could just be set to the `app/[app name]` directory, and just add that into the docs? I think it would also be good to exclude the directories key from `maker.schema.json` (and maybe also relocate those files to `app/[app name]` alongside the other config files).

I'm a bit busy at the moment but would be glad to make a PR in a few weeks if that's helpful
