### ISSUE TITLE
Make 'frontendProject' in 'nx-electron:make' optional

### ISSUE THREAD

**Issue by lailo** [bennymeg/nx-electron#170]
**Is your feature request related to a problem? Please describe.**
I'm building an app that doesn't require a UI besides the try menu but the `frontendProject` configuration in the project.json for the `nx-electron:make` requires to add a frontend app name.

**Describe the solution you'd like**
Make the `frontendProject` configuration in the `nx-electron:make` optional.

**Describe alternatives you've considered**
Instead of having a string and making it optional, we could have a list where you could leave empty or add multiple frontend app names.

**Additional context**
No additional context.

**Comment by bennymeg** [comment]
Added on v14!
