### ISSUE TITLE
Add squirrel support for nsis target

### ISSUE THREAD

**Issue by helen-dwa** [bennymeg/nx-electron#172]
**Is your feature request related to a problem? Please describe.**
I want to enable the auto updating for Windows 'nsis' target. So the file Update.exe (or Squirrel.exe) is to be included in the installer.

**Describe the solution you'd like**
Add some option to the config (for example "enableSquirrelUpdate": true)
"nsis": {
    "perMachine": true,
    "oneClick": false,
    "allowToChangeInstallationDirectory": true
  }

**Describe alternatives you've considered**
It works for target 'squirrel':
"win": {
    "target": [
      "squirrel"
    ]
  },
"squirrelWindows": {...}

**More info**
If to make a normal electron app using electron-builder (nsis), after installation there will be the following directory structure:
<.>
____app.exe
____<app-1.0.1>
________app.exe
________Squirrel.exe
So the file Squirrel.exe is required for a successful auto updating.

**Comment by bennymeg** [comment]
This feature should be requested from the `Electron Builder` team.
