### ISSUE TITLE
How to bundle multiple frontend apps to a single electron app.

### ISSUE THREAD

**Issue by aravindjaimon** [bennymeg/nx-electron#173]
**Is your feature request related to a problem? Please describe.**
I was creating a multi-window electron application. There came a situation where there was a transparent window with two actions "Accept" or "Reject". For this, I created another lightweight react application. But the nx-electron configuration only allows the packing of one react app.

**Describe the solution you'd like**
I wish we can accept ```frontendProjects``` instead of ```frontendProject``` and make it an array so that multiple frontend apps are packed into the same electron app.

**Describe alternatives you've considered**
If I need to achieve at the current scope how can I do it?

**Additional context**

**Comment by erick-rodriguez-lab49** [comment]
Usually, an Electron application contains only ONE JS APPLICATION. How you build the application could be related to how you build the application that electron will host.

If you use react-router for example, you can take advantage of it and create multiple sub-apps inside of the main app, and use such paths to load data in different windows.
