### ISSUE TITLE
unable to use nx-electron in nx 15.3

### ISSUE THREAD

**Issue by tbogard** [bennymeg/nx-electron#189]
**postinstall crashes after upgrading to nx 15.3**
after upgrading nx framework to 15.3, it seems the postinstall breaks nx-electron:

**To Reproduce**
1. nx migrate latest
2. npm i
3. postinstall throws the following error:

```bash
warning "nx-electron > rxjs-for-await@1.0.0" has unmet peer dependency "rxjs@^7.0.0".
[4/4] Building fresh packages...
[1/3] ⠈ nx
[2/3] ⠈ nx
error E:\StreamOverlayPro-dev\StreamOverlayPro-NX\streamoverlaypro\node_modules\nx-electron\node_modules\nx: Command failed.
Exit code: 1
Command: node ./bin/init
Arguments:
Directory: E:\StreamOverlayPro-dev\StreamOverlayPro-NX\streamoverlaypro\node_modules\nx-electron\node_modules\nx
Output:

$
```

I have tried to determine the source of the issue. still very preliminary.

**Expected behavior**
Build should exit successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, node 16.18.1
 - Nx Electron Version: 13.2.1
 - Nx Framework: 15.3

**Comment by tbogard** [comment]
not the best way, but apparently you can run `--ignore-scripts` to bypass the postinstall scripts. I will review if it makes it work or if there's the need to open a branch and pass a merge request.

**Comment by tbogard** [comment]
nope, it didn't work. still checking if I need to modify the test files since some imports on test and files moved on Nx 15.3

**Comment by tbogard** [comment]
Not closed here. still working on it.

**Comment by tbogard** [comment]
Some updates. NOT CLOSED.
1. Tests are failing on most of the schematics on WINDOWS. It should be transparent the test on mac/Linux/windows if the paths involved in the test are properly using path.join/path.resolve rather than a string. Tests show quite different things.
2. once I fix the tests, I will attempt to resolve the build using Nx 15.4.

Note: if you are using Nx 14.3, be aware that breaking changes will happen and probably I will add a required version of Nx to prevent breaking changes on version 14. Keep in mind that if @bennymeg doesn't update Nx Electron to Nx 15.4, I would eventually think on do it myself in a separate branch.

**Comment by montella1507** [comment]
i can confirm it is not possible even to generate application:

`marianbencat@Marians-Air diy-manager %  nx generate nx-electron:application

>  NX  Generating nx-electron:application

✔ What name would you like to use for the electron application? · diy-commander-electron
✔ In which directory should the electron application be generated? · apps
✔ What's the name of the web app in your workspace you'd like to use inside Electron? · diy-commander

 >  NX   The "path" argument must be of type string. Received undefined

   Pass --verbose to see the stacktrace.
`

**Comment by bennymeg** [comment]
@tbogard Thank you for working on the unit tests.
The release cycle of NX is quite short, and I do not have a lot of time to develop the package every week. Hence, the slow releases.
If you wish to work on v14 / v15 or adding new features, I would be more than happy to merge your PR's.
I am keeping developing and improving the package and hopefully release a new version (14) soon.

**Comment by tbogard** [comment]
If you teach me how to understand the migrations on Nx Schematics, I can put time into it absolutely. a lot changed and I would like to contact you via video call to understand better how you developed this package so I can contribute more efficiently.

**Comment by tbogard** [comment]
Checking over the tests:
- More likely tests need to be moved into their own directory for the reason that we need a "test" project data to work with. Logic and test in this case need to be totally separated.
- that said, I will proceed to rewrite those in a manner that is cross-platform (electron is cross-platform, so tests should be the same) so no inconsistencies with the paths happen at the moment of writing.

Wish me luck folks, this is a big one.

**Comment by AndrewRedican** [comment]
Good luck!

**Comment by bennymeg** [comment]
@tbogard it is common practice to place the test file adjacent to the module files.
I agree we need a test project; I think it could work by providing a link to the test project in each test file.

**Comment by tbogard** [comment]
That would be perfect, I will then remove the new test folder i was about to work.

**Comment by tbogard** [comment]
> @tbogard it is common practice to place the test file adjacent to the module files. I agree we need a test project; I think it could work by providing a link to the test project in each test file.

that will be perfect. in that aspect, test will not do anything outside of what is stated on the project file and that will make the test more consistent.

FYI, for migration to v14:
- Migrating nx to 14.8.6 which is the last head of 14
- electron migrated to 22.0.3? maybe we can move to this one since it is the latest stable version

That will put the repo in good standing when we migrate to 15.

**Comment by bennymeg** [comment]
yes, I will release it by the end of this week.

**Comment by codelocksdev** [comment]
Just adding my +1 to this issue. Looking forward to the upgrade/fix for v14 and v15. Thanks!

**Comment by jasonbdt** [comment]
+1 to this too, as I want to start using NX for my latest project along with nx-electron and Angular in its latest version.

I would like to help, but unfortunately I have no experience in working on open source projects.

**Comment by anbiniyar** [comment]
+1 Thank you for working on this! I am looking forward to it!

**Comment by bennymeg** [comment]
I have released a beta few days ago, if all goes well and no one will report an issue I will release a stable version in a couple of days.
I will try to release alpha for v15 quickly, but it will take a bit to release a stable v15. it seems Nrwl have done a lot of changes under the hood again.

**Comment by codelocksdev** [comment]
I appreciate the effort! I'll keep an eye out for the v15 alpha.

**Comment by tbogard** [comment]
@bennymeg note that v15 changed the cli tooling a lot, so you might be aware of breaking changes since v14. If you open a branch I can be able to contribute.

**Comment by bennymeg** [comment]
There is a branch for v15 with initial migrations, check it out. They change the architecture every other version, its hard to keep up with them.

**Comment by mtrefzer** [comment]
Are there any updates on the progress?

I need to upgrade a clients project to the actual nx version (15.8.x).
If you could provide an early alpha npm package, I'd be happy to test it on the mentioned project and give you my feedback.

@bennymeg BTW thanks for that lovely plugin :)

**Comment by tbogard** [comment]
I couldn't have enough time for this @mtrefzer , I will keep in touch @bennymeg to see if we can move from the stable branch of 14 to move into 15.

**Comment by e-oldman** [comment]
https://github.com/bennymeg/nx-electron/pull/196#issuecomment-1459649903

**Comment by bennymeg** [comment]
@mtrefzer I've published an alpha.

**Comment by mtrefzer** [comment]
@bennymeg I migrated my clients project with the alpha and everything worked. 
I just used the most recent electron version and added some overrides due to some vulnerabilities (Severity: high).

Here are the relevant parts of the `package.json`
```
{
  "engines": {
    "node": "18.15.0",
    "npm": "9.5.0"
  },
  "devDependencies": {
    "electron": "^24.0.0"
  },
  "overrides": {
    "electron-builder": "^24.2.0",
    "webpack": "^5.78.0"
  }
}
```

**Comment by codelocksdev** [comment]
Works great for me on nx v15.9.2

**Comment by Daneng66** [comment]
@codelocksdev how did you get it to work?

**Comment by abf7d** [comment]
Is there a timeline on when an installer willl be available?
