### ISSUE TITLE
VS Code Debug Configuration?

### ISSUE THREAD

**Issue by s4m0r4m4** [bennymeg/nx-electron#19]
**Is your feature request related to a problem? Please describe.**
This is a great starter for using electron in nx, thank you!!! I wanted to check to see if you had any suggestions on how to setup a debug profile for common IDEs, like VS code? I would definitely want to support hot reload for the angular UI, hot reload for the back-end main process is more of a nice-to-have.

**Describe the solution you'd like**
Include a launch.json (and potentially tasks.json) file in the repo for use in VS Code. Or update the documentation accordingly. Ideally this would leverage your existing nx serve command, but I'm still coming up the learning curve with electron so that might not be the best solution moving forward.

**Additional context**
I've tried making some headway myself, but haven't been able to get it to work yet.

Launch.json configuration:
```
{
	"name": "Red Hand: Main",
	"type": "node",
	"request": "launch",
	"protocol": "inspector",
	"runtimeExecutable": "${workspaceFolder:ci-web}/node_modules/.bin/electron",
	"runtimeArgs": [
		"--remote-debugging-port=9224",
		"../dist/apps/app-main/src" // path to directory with index.js
	],
	"windows": {
		"runtimeExecutable": "${workspaceFolder:ci-web}/node_modules/.bin/electron.cmd"
        },
	"preLaunchTask": "BuildMain",
}
```
Tasks.json task:

```
{
            "label": "BuildMain",
            "type": "npm",
            "script": "build-main",
            "group": "build",
            "problemMatcher": {
                "owner": "typescript",
                "source": "ts",
                "applyTo": "closedDocuments",
                "fileLocation": [
                    "relative",
                    "${cwd}"
                ],
                "pattern": "$tsc",
                "background": {
                    "activeOnStart": true
                }
            }
},
```

where `build-main` is defined in the root package.json:
`"build-redhand-main": "tsc -p apps/red-hand-main/tsconfig.app.json --resolveJsonModule",`

Though ideally we'd update the task to be of type "typescript" to avoid needing another package.json entry. And of course the tsconfig.app.json has the comiple option: `"outDir": "../../dist"`

The error I run into with the configuration above is:
![image](https://user-images.githubusercontent.com/8257287/79869331-ccae3480-83a6-11ea-98e4-c5d472f173c3.png)

**Comment by bennymeg** [comment]
> Include a launch.json (and potentially tasks.json) file in the repo for use in VS Code. Or update the documentation accordingly. Ideally this would leverage your existing nx serve command, but I'm still coming up the learning curve with electron so that might not be the best solution moving forward.

I am not sure adding such configuration would be a good idea since many developers use different IDEs then VsCode like webstorm. I would be happy to add a debug section to the documentation.

> I wanted to check to see if you had any suggestions on how to setup a debug profile for common IDEs, like VS code?

Try using the following configurations:
- Launch.json configuration:
```
{
            "name": "Debug Main Process",
            "type": "node",
            "request": "launch",
            "port": 5858,
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
            "windows": {
              "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
            },
            "args" : ["--inspect-brk=5858", "dist/apps/{electron-app-name}/main.js"],
            "outputCapture": "std",
            "preLaunchTask": "BuildMain"
}
```
- Tasks.json task:
```
{
        "label": "build-main",
        "type": "npm",
        "script": "build-main",
        "group": "build",
        "problemMatcher": ["$eslint-stylish"]
}
```
where `"build-main": "nx build {electron-app-name}"` in your package.json

**Comment by s4m0r4m4** [comment]
Thanks for the quick response! 

Sure that makes sense to me (adding the docs, not the files). Thanks for those starters for the config files, they were helpful. 

One thing I might add to the docs is that you can set `--remote-debugging-port=xxxx` in the `args` in the static debugger launch.json so that you can attach a debugger to that port for the user interface.

Thanks again!
