### ISSUE TITLE
maker.options.json vs. angular.json settings

### ISSUE THREAD

**Issue by s4m0r4m4** [bennymeg/nx-electron#20]
Seriously great work with this plug-in, the more I use it the more I'm thankful!

**Describe the bug**
There is some confusion over where to set `asar: true/false`. The schema from maker.options.json allows for an asar value at the root level, which is in line with the electron-builder schema. But nx-electron also supports an `asar` setting in angular.json.

Regardless of the value of the asar setting in maker.options.json, when I run nx make <project-name> it displays the following warning:

- `asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available`

***Code***
In make.impl.ts, the function `mergePresetOptions` is correctly returning an options dictionary that reflects the asar setting from maker.options.json. `_createBaseConfig` then creates its own asar setting to be false since I didn't set it in angular.json. And then `_createConfigFromOptions` overwrites the asar setting from maker.impl.ts with the value from `_createBaseConfig`.

**Expected behavior**
Here's how I would approach it: I would remove the asar setting from angular.json and only allow it in maker.options.json. This does limit the flexibility of build configs (can't have one build for asar=true, one for asar=false), but to overcome that I would suggest putting the name/path to the maker.options.json file in each maker config in angular.json (rather than hardcoding in maker.impl.ts), and then the user can have multiple maker.options.json for each config they want. They can even extend a common base config and then just customize to each maker need. It's just my opinion, but I do think it would help avoid duplicate settings while using the electron-builder config wherever possible.

**Other Config Notes**
I took some time to work through some other configuration settings and had some feedback/thoughts:
- I'm running into an issue with the version of the app. Right now it only uses the version from package.json. This is kinda a bigger problem with Nx in general (tying all app versions to a single property in package.json), but I think you have an opportunity to fix it for electron apps in your plugin. To do this, I would suggest overwriting the `version` from package.json with the `buildVersion` from maker.options.json if it is provided, otherwise fallback to the `version` in package.json.
- the default files settings in make.impl.ts are probably worth documenting, it took me a while to figure out what it was doing.
- the link under [Making an Electron Application](https://github.com/bennymeg/nx-electron#making-electron-application) on the word "here" incorrectly leads to the [packaging options](https://github.com/bennymeg/nx-electron/blob/master/docs/packaging.md) doc page, I believe it should lead to the [making options](https://github.com/bennymeg/nx-electron/blob/master/docs/making.md) doc page.
- When making an app, it creates a resources folder, which contains a subfolder called "app", which contains subfolders for the main and front-end projects. I can't figure out where the name "app" comes from (maybe my own config?). I care about this because in my maker.options.json, I have an "extraResources" entry that's supposed to copy some resources over, and it has to know about that folder name in the "to" field:
```
"extraResources": [
     {
         "from": "apps/<app-name>/src/resources",
         "to": "app/<app-name>/resources",
         "filter": ["**/*"]
     }
   ],
```
If "app" comes from nx-electron, I would suggest changing it to "apps" so it matches the default nx directory structure, though this isn't a big deal.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Nx Electron Version: 9.0.0-beta5

**Comment by bennymeg** [comment]
> Seriously great work with this plug-in, the more I use it the more I'm thankful!

Thank you!

> nx-electron also supports an asar setting in angular.json.

The Idea was to support it in the angular-console and not that it would be available in both of the configuration files. I will just remove it, it cause a lot of confusion.

> Regardless of the value of the asar setting in maker.options.json, when I run nx make it displays the following warning

I fixed it, will be available on the next release.

> to overcome that I would suggest putting the name/path to the maker.options.json file in each maker config in angular.json (rather than hardcoding in maker.impl.ts), and then the user can have multiple maker.options.json for each config they want.

Good idea, I will do that in a later update, after v9 will be released.

>  I would suggest overwriting the version from package.json with the buildVersion from maker.options.json if it is provided, otherwise fallback to the version in package.json.

Sounds good.

> the link under Making an Electron Application on the word "here" incorrectly leads to the packaging options doc page, I believe it should lead to the making options doc page.

Thanks, I will fix it.

> When making an app, it creates a resources folder, which contains a subfolder called "app"

That's a requirement of electron, I do not think it can be changed.

**Comment by bennymeg** [comment]
> I'm running into an issue with the version of the app. Right now it only uses the version from package.json. This is kinda a bigger problem with Nx in general (tying all app versions to a single property in package.json), but I think you have an opportunity to fix it for electron apps in your plugin. To do this, I would suggest overwriting the version from package.json with the buildVersion from maker.options.json if it is provided, otherwise fallback to the version in package.json.

I have given some thought to it and I think what you are asking is not possible since the app version is decided on build time and the build version on make time and I don't wish to mix them.

**Comment by s4m0r4m4** [comment]
Thanks for the reply, your responses make sense. The thing I'm having trouble figuring out is that when I specify buildVersion in maker.options.json (say, `"buildVersion": "1.2.3"`), it seems to have no effect on the produced executable (it's name still has "`0.0.0`" in it, from package.json). What is buildVersion supposed to affect if not that?

I might be reading it wrong, but in the [electron-builder docs](https://www.electron.build/configuration/configuration#configuration) seem to indicate that if you don't set buildVersion it will default to the version in package.json. I assumed if you do set buildVersion it would then override the version from package.json, which would be ideal for a monorepo situation like this.

**Comment by bennymeg** [comment]
I think what you are looking for is the `artifactName` property in combination with some [macros](https://www.electron.build/file-patterns#file-macros):
```json
"artifactName": "${productName}-${buildVersion}.${ext}"
```
-OR-
```json
"artifactName": "${productName}-${env.ENV_NAME}.${ext}"
```

**Comment by s4m0r4m4** [comment]
Oh I see, thank you!
