### ISSUE TITLE
Different auto updaters

### ISSUE THREAD

**Issue by Hemesh-Unka** [bennymeg/nx-electron#203]
Hello!

Really appreciate the hard work with this repo! I had a question to the wider community.

Has anyone had any luck of changing out the current auto updater? I’ve tried swapping out the current one for [Electron updater](https://www.npmjs.com/package/electron-updater) .

Compiles and builds alright. But when opening the built application I am getting the following.

![D7A1AD57-61D6-49E0-978A-9882E226A6F3](https://user-images.githubusercontent.com/12001682/216762443-b86f1297-32d7-4573-ba87-28502bb707cf.png)

Am I missing something in the compiler settings or need to create a custom webpack config. Any help would be greatly appreciated.

**Comment by bennymeg** [comment]
Try adding `electron-updater` as an external dependency.

**Comment by Hemesh-Unka** [comment]
That seemed to do the trick. Thanks @bennymeg
