### ISSUE TITLE
Unable to override buildResources directory

### ISSUE THREAD

**Issue by atali** [bennymeg/nx-electron#21]
I am trying to override the buildResources directory when trying to make the distribuable package but when running the make command, my configuration disappear and it's overridden by the default value 'build'

```
    "directories": {
      "buildResources": "resources",
    },
```

The code below is overriding the option
https://github.com/bennymeg/nx-electron/blob/68bca2a6af04707e6a0086ad34f4af59f8a7e091/src/builders/make/make.impl.ts#L108

**Comment by bennymeg** [comment]
Fixed. Will be available on the next release.
