### ISSUE TITLE
Error with typescript

### ISSUE THREAD

**Issue by francescodepaloo** [bennymeg/nx-electron#211]
TypeError: (0 , typescript_1.readTsConfig) is not a function
    at getBaseWebpackPartial (.\node_modules\nx-electron\src\utils\config.js:19:72)

anyone who can help me?

**Comment by mpellerin42** [comment]
I've got the exact same problem after I upgraded nx and angular to version 15. 
nx-electron is only version 14, so there might be some conflicts.

**Comment by Mihai-github** [comment]
+1
