### ISSUE TITLE
Packaged Electron-React app renders a blank page

### ISSUE THREAD

**Issue by VladislavMaksimov** [bennymeg/nx-electron#212]
Hello, I use nx-electron with React and package a simple app with the Nx's welcome page.  It works well in dev mode, but after packaging, the app renders a blank page. 

My `main` Electron app and `renderer` React app are in a `client` folder. After generating the Electron app with nx-electron I changed a `<base href="/" />` to `<base href="./" />` in `index.html` of the React app, and made some changes in `project.json`:  

from
```
"package": {
      ...
      "options": {
        "name": "client-main",
        ...
      }
},
```

to
```
"package": {
      ...
      "options": {
        "name": "client/main",
        ...
      }
},
```

because I had an error
```
ENOENT: no such file or directory, open 'C:\...\my-project\dist\apps\client-main\index.js'
```

Before I changed a `<base href="/" />` I had an error connected with paths after packaging; now I don't have any errors, but nothing is being rendered either.

Also tried to change a `baseHref` option in the Electron app's `project.json`, but it didn't change anything. After that, I added a `HashRouter` to the React app (although I have only one page in it and don't need the router), but it also didn't help.

What should I do?

**My OS and tools versions**

- platform: win32
- arch: x64
- electron: 22.3.6
- react: 18.2.0
- nx: 14.8.8
- nx-electron: 14.0.2

**Comment by VladislavMaksimov** [comment]
I'm sorry, accidentally opened the issue before finished writing, now I will edit it.

**Comment by VladislavMaksimov** [comment]
Also tried to change the version of Nx to `14.0.2` and to change the build path of the Electron app to `client/main`, but none of that worked.

**Comment by bennymeg** [comment]
All the aplicatioins should reside inside the apps folder. Nesting is not supported.

**Comment by VladislavMaksimov** [comment]
> All the aplicatioins should reside inside the apps folder. Nesting is not supported.

Thanks! Thought that nesting is supported and even required because for some reason there is a directory input when you use the Nx console and it's being rendered as a required field.

![image](https://user-images.githubusercontent.com/46715602/233500011-cf9b3e39-7ddb-473a-835b-a186d2ebac0f.png)
