### ISSUE TITLE
Usage with electron-devtools-installer

### ISSUE THREAD

**Issue by VladislavMaksimov** [bennymeg/nx-electron#214]
Hello, I'm trying to add electron devtools via [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer).

Firstly I added the latest version of **electron-devtools-installer** and received the `ManifestError` (possibly because the extension in the `3.x.x` version of the lib changed manifest to v3). Then I downgraded the version of the lib to `2.2.4`, and now I'm getting the new error: `TypeError: BrowserWindow.addDevToolsExtension is not a function`.

I tried to install the extension with `REACT_DEVELOPER_TOOLS` id into the `App.onReady` and in `main.ts` into the `app.whenReady().then()` method.

Is it possible to use **electron-devtools-installer** with **nx-electron**?

**My OS and tools versions**

- platform: win32
- arch: x64
- electron: 22.3.6
- react: 18.2.0
- nx: 14.8.8
- nx-electron: 14.0.2

**Comment by bennymeg** [comment]
Yes, it's possible. I am using v3 for a couple of years.

**Comment by VladislavMaksimov** [comment]
> Yes, it's possible. I am using v3 for a couple of years. It's probably due to the reason you stated. downgrading the package by itself won't solve the issue. Try deleting the devtool extension and then to reinstall [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer) maybe it would download the old version of the extension. If not, You might need to wait for the extension developers (not MarshallOfSound) to fix this issue for electron.

Thanks for the answer. The real problem wasn't in the **devtools** or **nx-electron**, I just forgot to add **electron-debug** :')
These errors are also thrown in other electron projects, because electron [doesn't support](https://github.com/electron/electron/issues/36545) `chrome.scripting` API.

However, what do you think about generating code that installs devtools with **electron-devtools-installer** via **nx-electron**? Devtools seem essential for the electron devs.
