### ISSUE TITLE
Any plan to support bundle with vite

### ISSUE THREAD

**Issue by vuggy17** [bennymeg/nx-electron#215]
**Is your feature request related to a problem? Please describe.**
Vite is faster, and there is a plugin that can be used to simplify the complex of manage ipcs interface, take a look at [this repo](https://github.com/cawa-93/vite-electron-builder) he use [this plugin](https://github.com/cawa-93/unplugin-auto-expose) to manage ipc exposes.

**Describe the solution you'd like**
I would like the library to provide an option to bundle with Vite. This could be implemented by adding a new configuration option or flag that allows users to choose between bundling with Webpack or Vite. 
Like nx-react plugin: `nx create-app myapp --bundler=vite`

**Describe alternatives you've considered**

**Additional context**
Thank you for considering this feature request.

**Comment by bennymeg** [comment]
Sure, I'll be happy to recieve a PR.
All is needed to do is:
1. Add a file similar to [this one](https://github.com/bennymeg/nx-electron/blob/master/packages/nx-electron/src/utils/run-webpack.ts) in vite.

2. Add an option to select the bundler [like here](https://github.com/nrwl/nx/blob/c688df69b2427927c42feb3a89434743c14f5e29/packages/react/src/generators/application/schema.json#L182).

**Comment by WillPoulson** [comment]
@bennymeg I'm wondering how crazy it would be to migrate to `electron-forge` to deal with the compiling work. Purely an idea at this point, I haven't looked into how possible this would be.

But I suppose that would dirty this project into `nx-electron-forge` more than a base `nx-electron`

Forge supports both webpack and vite and if we could integrate it into nx executors that might remove quite a lot of heavy lifting this package has to do.

What are your thoughts on this?

**Comment by bennymeg** [comment]
@WillPoulson I did not have a good experience with electron-forge in the past for complex applications. But a long time has pass and it seems that electron adopted them as their build tool so it might have changed. 
It wouldn't be a small task so we will need to understand in depth what we will gain and loose from it.

Regarding 'electron-vite', sure, [@nx/vite](https://github.com/nrwl/nx/tree/c688df69b2427927c42feb3a89434743c14f5e29/packages/vite) might be a good solution as well.

**Comment by leaftail1880** [comment]
This is closed as completed, but no vite support was added. I saw you mentioning this on other issue:
> I wanted to try and add vite support for this version, but I see I won't have a chance.

So is vite support being worked on by you or i can make pr by myself?

**Comment by bennymeg** [comment]
If you think you can contribute it would be very appreciated.
