### ISSUE TITLE
Nx-Electron in an Integrated Monorepo

### ISSUE THREAD

**Issue by HealMah** [bennymeg/nx-electron#220]
Dear Author Nx-Electron!
First, I want to appreciate your efforts and sacrifices, thank you so much.

*ISSUE*
When used in an intergrated monorepo, nx-electron electron picks the MAIN PACKAGE.JSON for information. This. is problematic when when you have or wish to have several apps with slightly different versions. FLEXIBILITY ISSUE.

*FEATURE REQUEST *
It will be very good, if there should be room for configuring what package.json should be used, Default main one or project related one!

Once again, God Bless You!

**Comment by bennymeg** [comment]
I'll link this to #228
