### ISSUE TITLE
Integration for Nx v16

### ISSUE THREAD

**Issue by abf7d** [bennymeg/nx-electron#221]
**Is your feature request related to a problem? Please describe.**
I have been working with an Angular project and need to upgrade to v16. I also need an electron app. What is the timeline to integrating with Nx 16.

**Describe the solution you'd like**
I wish to create an electron project in Nx 16.

**Describe alternatives you've considered**
The only alternative is to create an electron project out of Nx 15.9.

**Comment by MrTob** [comment]
is it possible to use Angular 16?

**Comment by bennymeg** [comment]
You should use the same major version.
