### ISSUE TITLE
Passing version with extraMetadata is not used in environments __BUILD_VERSION__

### ISSUE THREAD

**Issue by mtrefzer** [bennymeg/nx-electron#224]
**Describe the bug**
When I pass a version with `--extraMetadata.version=x.y.z` I expect that this version is used in `environments` `__BUILD_VERSION__`

**To Reproduce**
1. set the `package.json` `version` to `0.0.1`
2. run `nx run <electron-app-name>:build --extraMetadata.version=0.0.2`
3. run `nx run <electron-app-name>:make --extraMetadata.version=0.0.2`
4. `:build` uses the `version` of `package.json` while `:make` uses the passed `extraMetadata.version`, which leads to inconsistent autoupdates with `electron-updater` 

**Expected behavior**
`nx run <electron-app-name>:build --extraMetadata.version=0.0.2` should use the passed value instead of the one from package.json 

**Desktop:**
 - OS: Ubuntu 22.04
 - Nx Electron Version 15.0.0
 
**Additional context**
`utils/config.ts l.86`
```
new DefinePlugin({
        __BUILD_VERSION__: JSON.stringify(require(join(options.root, "package.json")).version),
        __BUILD_DATE__: Date.now()
      })
```

**Comment by alkrobinson** [comment]
@bennymeg any updates on this? Trying to setup a update server but this is blocking me.

**Comment by bennymeg** [comment]
Will be published in the next release.

**Comment by alkrobinson** [comment]
Any update on this or a workaround? Is it possible to write/update the version in the asar packaged `package.json` after make? We are really trying to setup an update server/show accurate versions in our application and this is a blocker.

**Comment by bennymeg** [comment]
Released
