### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by atali** [bennymeg/nx-electron#23]
**Describe the bug**
I am trying to publish my app with a custom plublisher but the configuration generated is not correct

**To Reproduce**
When running the following command line :
```
nx run ev-electron:make --publish=always
```

My workspace.json 

```
        "make": {
          "builder": "nx-electron:make",
          "options": {
            "name": "my-app",
            "frontendProject": "my-frontend",
            "out": "dist/executables",
            "directories": {
              "buildResources": "./dist/build"
            },
            "win": {
              "icon": "icons/desktop.ico",
              "target": [
                {
                  "target": "msi",
                  "arch": [
                    "x64"
                  ]
                }
              ]
            },
            "linux": {
              "target": "zip",
            },
            "mac": {
              "icon": "icons/icon.icns",
            },
            "publish": {
              "provider" : "custom",
              "publishAutoUpdate" : true,
              "publisherName": ["My Company"]
            },
            "generateUpdatesFilesForAllChannels": true
          }
        }
```

**Expected behavior**
according to https://www.electron.build/configuration/publish#how-to-publish
I was expecting nx electron will call electron builder with the following parameters:

`electron-builder --config dist/executables/builder-effective-config.yaml --publish always`

**Screenshots**
nx-electron is writing the parameter "always" instead of passing it to electron builder directly 

![image](https://user-images.githubusercontent.com/369628/80480098-10142000-891e-11ea-8dbf-5dfd1ed25b43.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Nx Electron Version 9.0.0-beta.6

**Comment by bennymeg** [comment]
please update your package and try the following command:
`nx run ev-electron:make --publishPolicy=always`

**Comment by atali** [comment]
nice good job :-) thanks a lot .
