### ISSUE TITLE
No cached ProjectGraph is available.

### ISSUE THREAD

**Issue by MrTob** [bennymeg/nx-electron#237]
When running the script "build-electron": "nx build desktop" i got the "[readCachedProjectGraph] ERROR: No cached ProjectGraph is available." error

i use angular and nx in a monorepo

 - OS. Win11
 - Angular Version: 16
 - Nx Electron Version 15.1.0

**Comment by alljinx** [comment]
I think you are using nx-electron 15 with NX 16, wich is not totally compatible yet.

**Comment by bennymeg** [comment]
Nx Electron / Nx / Angular should all be on the same major version.
