### ISSUE TITLE
Cannot find module '@nrwl/jest'

### ISSUE THREAD

**Issue by dmatora** [bennymeg/nx-electron#239]
running `nx g nx-electron:app test` throws `NX   Cannot find module '@nrwl/jest'`

**To Reproduce**
1. `npx create-nx-workspace@15`
2. `npm install -D nx-electron`
3. `nx g nx-electron:app test`
4. See `NX   Cannot find module '@nrwl/jest'`

**Expected behavior**
Expecting nx-electron to build electron app

**Desktop (please complete the following information):**
 - macOS 11.6.8
 - Nx Version 15.9.4
 - Nx Electron Version 15.1.0

---

Installed it manually (and few other missing dependancies) and got project working though

**Comment by dmatora** [comment]
As mentioned at #217 , unfortunately it doesn't

**Comment by bennymeg** [comment]
I think nx introduces a breaking change without changing the major release.
I believe that if you would downgrade nx to earlier v15 version it would be resolved.
They change some of the packages from @nrwl to @nx
