### ISSUE TITLE
Unable to load electron-builder.env

### ISSUE THREAD

**Issue by atali** [bennymeg/nx-electron#24]
**Describe the bug**
electron-builder.env is not read by nx-electron

**To Reproduce**
- create an nx electron project
- create a file electron-builder.env
```
FOO=BAR
```
- try to access the variable from `process.env.FOO`

**Expected behavior**
as stated by the documentation here https://www.electron.build/configuration/configuration#environment-variables-from-file, when the file electron-builder.env is in the current directory of the electron, electron-builder should load it

**Desktop (please complete the following information):**
 - OS: MacOs
 - Nx Electron Version 9.0.0-beta.7

**Additional context**
I use that file to load some variables environment

**Comment by bennymeg** [comment]
Sorry, as it stated on the documentation you linked, this feature is `"supported only for CLI usage"`.

**Comment by atali** [comment]
Thanks benny, I read the documentation to quickly.

I am lucky because you are using dotenv. I am writing a custom publisher and using dotenv was my only option to get values.

Thanks for all your works
