### ISSUE TITLE
ERR_FILE_NOT_FOUND in packaged app

### ISSUE THREAD

**Issue by dmatora** [bennymeg/nx-electron#240]
packaged app is looking for assets from a wrong folder, getting `GET file:///assets/index-e74d1eec.js net::ERR_FILE_NOT_FOUND`

**To Reproduce**
1. `npx create-nx-workspace@15`
2. `npm install -D nx-electron`
3.1 `nx g @nrwl/react:app desktop-react`
3.2. add missing libraries
4. `nx g nx-electron:app desktop-electron --frontendProject=desktop-react`
5. `nx run desktop-react:build:production`
6. `nx run desktop-electron:build:production`
7. `nx run desktop-electron:package`
8. run `dist/packages/mac/electron-react.app`
9. See `ERR_FILE_NOT_FOUND` in inspector

**Expected behavior**
Expecting nx-electron to package working electron app

**Desktop (please complete the following information):**
 - macOS 11.6.8
 - Nx Version 15.9.4
 - Nx Electron Version 15.1.0

![image](https://github.com/bennymeg/nx-electron/assets/647062/99a940db-a12c-4aa9-a4bc-4167fb8ec2fe)

**Comment by bennymeg** [comment]
Read the docs about setting the href.

**Comment by dmatora** [comment]
@bennymeg are you talking about setting it to './' ?
I did that

**Comment by dmatora** [comment]
Ok, I've had a closer look and realized that you were talking about baseHref in workspace.json or in `nx build my-app --baseHref="./"`
Initially I though you're talking about <base href="./" /> in apps/desktop-react/index.html
Now I see these also add ./ prefix for assets, which is also necessary
Added
```
      "configurations": {
        "development": {
          "mode": "development",
          "baseHref": "/"
        },
        "production": {
          "mode": "production",
          "baseHref": "./"
        }
      }
    },

```
to `apps/desktop-react/project.json` and things now work beautifully.
Thanks for implementing that!

**Comment by bennymeg** [comment]
Out of interest, why did you used different "baseHref" setting?
It should be the same.

**Comment by dmatora** [comment]
so that both production build and development serve are working (or else one of them don't )
