### ISSUE TITLE
Override webpack configuration

### ISSUE THREAD

**Issue by atali** [bennymeg/nx-electron#25]
I am trying to override the webpack configuration with the webpackConfig property as you can see on schema for the builder "build" 

https://github.com/bennymeg/nx-electron/blob/7fce52b87940a5b2ccab1c563e7f122aefb4d620/src/builders/build/schema.json#L113

But it doesn't seem to take into account my configuration.

Not sure but is it possible to load the custom webpack confile file in the file [src/utils/electron.config.ts](https://github.com/bennymeg/nx-electron/blob/7fce52b87940a5b2ccab1c563e7f122aefb4d620/src/utils/electron.config.ts#L70)

Code should be like the following :
```
export function getElectronWebpackConfig(options: BuildElectronBuilderOptions) {
  return mergeWebpack(getBaseWebpackPartial(options), getElectronPartial(options), loadCustomWebPackConfig(options.webpackConfig)); // was array
}
```

**Comment by atali** [comment]
my use case is about transpiling a preload script from ts to js . Webpack actually is transpiling everything into a main.js file. I would like to have the ability to provide another typescript to be loaded by Electron at runtime.

More information [here](https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content)

```js

const mainWindow = new BrowserWindow({
  webPreferences: {
    preload: path.join(app.getAppPath(), './preload')
  }
})

mainWindow.loadURL('https://example.com')
```

**Comment by bennymeg** [comment]
If you provide a external configuration it will override the current electron webpack configuration:

https://github.com/bennymeg/nx-electron/blob/7fce52b87940a5b2ccab1c563e7f122aefb4d620/src/builders/build/build.impl.ts#L40-L47

How do you provide your external configuration?

**Comment by atali** [comment]
Sorry, my bad, I set the webpackConfig property in the wrong section
