### ISSUE TITLE
Issue running nx serve

### ISSUE THREAD

**Issue by abelabbesnabi** [bennymeg/nx-electron#257]
I'm trying to run my app that is in nx by issuing command: nx run my-app:serve but I get this error: Cannot find module '@nx/workspace/src/utilities/buildable-libs-utils'
I looked in the workspace folder under nx in node_modules, and sure enough, it's not there. I have all my packages updated. Not sure what to do here :(

**Comment by orestisioakeimidis** [comment]
@abelabbesnabi You are probably using latest NX, version `17.0.2` at the time. The utility functions have been moved to the `@nx/js` package inside `@nx/js/src/utils/buildable-libs-utils`.

It looks like this package is not compatible with NX version 17.

@bennymeg Do you need any help with making it compatible with latest NX?

**Comment by bennymeg** [comment]
@abelabbesnabi v17 is not supported yet. Please read the docs. Also, please provide more data next time you encounter an issue.
@orestisioakeimidis I would be happy for some help if you already know what nrwl deprecated this time.

**Comment by abelabbesnabi** [comment]
@bennymeg Got it. I didn't know what else to provide as info. Yes, I'm using latest nx. It would be amazing if you guys can make it compatible with the latest nx.

**Comment by bennymeg** [comment]
It seems someone already working on a PR to fix the broken dependency for v17.

**Comment by abelabbesnabi** [comment]
That is such great news. Thank you!
