### ISSUE TITLE
"files" property is overriden by the default configuration

### ISSUE THREAD

**Issue by atali** [bennymeg/nx-electron#26]
**Describe the bug**
I am trying to copy extra files to the package but my properties files are overridden. We are stuck because of this error :-(

**To Reproduce**
just create a new workspace.json or angular.json
```
              "files": [
                {
                  "from": "dist/apps/myapp/app/",
                  "to": "my-dist",
                  "filter": ["myfile.js"]
                }
              ]
```

**Expected behavior**
It should merge the default files array with the provided by the user

[make.impl.ts](https://github.com/bennymeg/nx-electron/blob/c8f7a24d027dc978419b370c67d04154bd506002/src/builders/make/make.impl.ts#L113)

```
function _createBaseConfig(options: MakeElectronBuilderOptions, context: BuilderContext): Configuration {
  return {
    directories: {
      ...options.directories,
      output: join(context.workspaceRoot, options.out)
    },
    files: [
      './package.json',
      '!**/*.js.map',
      {
          from: `./dist/apps/${options.frontendProject}`,
          to: options.frontendProject,
          filter: ['*.*', 'assets']
      },
      {
          from: `./dist/apps/${options.name}`,
          to: options.name,
          filter: ['main.js', 'assets']
      },
      {
          from: `./dist/apps/${options.name}`,
          to: '',
          filter: ['index.js']
      }
    ]
  };
}
```

I think the solution is to only merge both arrays ( the default one and the one coming from options.files
I have pushed a PR to fix it. let me know if it's ok ?

**Desktop (please complete the following information):**
 - OS:  MacOs
 - Nx Electron Version 8.2.4

**Comment by atali** [comment]
Thanks, it works :-)

**Comment by bennymeg** [comment]
@atali **Thank you** for fixing it =]
