### ISSUE TITLE
Build windows app (*.exe) on linux platform

### ISSUE THREAD

**Issue by FridaCai** [bennymeg/nx-electron#276]
Hi Team,

We are trying to build windows app (*.exe) on linux build machine and meet following error:![截屏2024-01-21 20 55 53](https://github.com/bennymeg/nx-electron/assets/12479174/ad332633-be5b-474d-939c-3acbdc6e1451)

We can solve the problem by adding following line before build:

https://github.com/bennymeg/nx-electron/blob/0d194ccb2c330b40656a163dfb29af2797403d77/packages/nx-electron/src/executors/package/executor.ts#L83

`normalizedOptions.win=[]`

more information can be find here: https://github.com/electron-userland/electron-builder/blob/277341000a87abaa65a7985854c06e88ed5938b9/packages/electron-builder/src/builder.ts#L89C1-L89C26

Although we have approach to solve this problem, it is not good practice to modify framework code in application project. So may I have your advice about how to config/use nx-electron properly in this case? Thanks in advance and look forward for your reply. Feel free to let me know if you need more details.

**Comment by bennymeg** [comment]
Thanks.

**Comment by bennymeg** [comment]
This might be related to how you defined the platforms / arch in the build [configuration](https://www.electron.build/cli#target).
What you did is simply override the configuration, so electron builder executed in its default behavior.

I have not tested multi-platform builds with nx-electron (I suspect this might not work), please advise [this document](https://www.electron.build/multi-platform-build) going forwards.
I would recommend compiling on a native platform if possible.
I will close this for now, but please continue sharing your findings in this thread.
