### ISSUE TITLE
Ability to add webpack entries to transpile multiples files in distinct files

### ISSUE THREAD

**Issue by atali** [bennymeg/nx-electron#28]
**Is your feature request related to a problem? Please describe.**
Actually, nx-electron produces only a main.js and we are unable to have the possibility to provide other files to be transpiled at the same time.

**Describe the solution you'd like**
in workspace.json or angular.json, is it possible to provide a new property webpackEntries ?

```
build": {
          "builder": "nx-electron:build",
          "options": {
            "outputPath": "dist/apps/myapp",
            "main": "apps/myapp/src/main.ts",
            "tsConfig": "apps/myapp/tsconfig.app.json",
            "webpackEntries": [
              { file1: "apps/myapp/src/app/file1.ts"},
              { file2: "apps/myapp/src/app/file2.ts"}
            ]
          },
```

**Describe alternatives you've considered**
I tried to use webpackConfig but I lose all your default configuration that I want to keep

**Comment by bennymeg** [comment]
Are you referring to [this](https://webpack.js.org/guides/code-splitting/#entry-points)?
Would something like that will solve the issue?

angular/nx.json
```json
build": {
          "builder": "nx-electron:build",
          "options": {
            "outputPath": "dist/apps/myapp",
            "main": "apps/myapp/src/main.ts",
            "tsConfig": "apps/myapp/tsconfig.app.json",
            "webpackEntries": {
              file1: "apps/myapp/src/app/file1.ts",
              file2: "apps/myapp/src/app/file2.ts"
            }
          },
```

webpackConfig
```js
module.exports = {
  entry: {
    ...webpackEntries
    main: './src/index.js',
  },
  ...
};
```

**Comment by atali** [comment]
Yes exactly ! It will solve my issue :-)

**Comment by bennymeg** [comment]
feature added to `v9.0.0-beta.10`

**Comment by atali** [comment]
as usual, great job. it works !
