### ISSUE TITLE
package command is failing due to unable to import ES module `strip-json-comments` using `require()`

### ISSUE THREAD

**Issue by yuryturing** [bennymeg/nx-electron#288]
**Describe the bug**
Unable to execute `package` command after upgrading to `nx-electron@18.0.0` due to
```
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\projects\testing-electron-support\node_modules\nx-electron\node_modul
es\strip-json-comments\index.js from C:\projects\testing-electron-support\node_modules\nx-electron\src\executors\package
\executor.js not supported.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nx Electron Version: 18.0.0

**Root case**
Dependency version for `strip-json-comments` has been upgraded `^3.1.1 --> ^5.0.1`.

The latest version of the dependency does not support commonjs imports, so transpiled code is not working any more.

```
const strip_json_comments_1 = tslib_1.__importDefault(require("strip-json-comments"));
```

**Comment by bennymeg** [comment]
Tnx, fixed.

**Comment by pg17** [comment]
Hi, this issue has been reintroduced in branch `feature/v19` / release `19.0.0-alpha.0`.

**Comment by bennymeg** [comment]
I re-patched it, tnx.
