### ISSUE TITLE
Can't install electron in a new NX monorepo version 19.0.2

### ISSUE THREAD

**Issue by abelabbesnabi** [bennymeg/nx-electron#291]
![Screenshot 2024-05-10 094401](https://github.com/bennymeg/nx-electron/assets/5861874/ce4e2e7c-1d39-44a3-b3f2-e2dfbd575ace)

**Comment by YeomansIII** [comment]
Please simply try using package.json overrides field to solve this error.

```json
{
  "name": "your-project-name",
  "version": "1.0.0",
  "scripts": {
    "start": "nx serve"
  },
  "dependencies": {
    "nx": "latest"
  },
  "devDependencies": {
    "nx-electron": "^19.0.2"
  },
  "overrides": {
    "nx-electron": {
      "@nx/workspace": "19.0.2"
    }
  }
}
```

**Comment by abelabbesnabi** [comment]
I'll try. Thank you

> Please simply try using package.json overrides field to solve this error.
> 
> ```json
> {
>   "name": "your-project-name",
>   "version": "1.0.0",
>   "scripts": {
>     "start": "nx serve"
>   },
>   "dependencies": {
>     "nx": "latest"
>   },
>   "devDependencies": {
>     "nx-electron": "^19.0.2"
>   },
>   "overrides": {
>     "nx-electron": {
>       "@nx/workspace": "19.0.2"
>     }
>   }
> }
> ```

**Comment by bennymeg** [comment]
The reason that it does not work is the there is no nx-electron v19 yet
