### ISSUE TITLE
Not working in Angular monorepo

### ISSUE THREAD

**Issue by CoolTrainerEX** [bennymeg/nx-electron#305]
I imported nx-electron to an angular monorepo and when I try to use it (i.e. serve/build), the same error returns:
```
Cannot read properties of undefined (reading 'projects')
```
I have changed base href to "./" and used webpack, as the readme suggested. I am just a beginner, so I might just be overlooking something. Any help would be appreciated. Thanks!

**Comment by julianpoemp** [comment]
Got the same error. Seems like Nx v20 is breaking something. Nx 19 still worked so far.

**Comment by o-glethorpe** [comment]
Same here
TypeError: Cannot read properties of undefined (reading 'projects')
node_modules/nx-electron/src/utils/workspace.js:5:52

**Comment by eweap** [comment]
```
const { sourceRoot, root } = context.workspace.projects[context.projectName];
```

should become:

```
const { sourceRoot, root } = context.projectsConfigurations.projects[context.projectName];
```

**Comment by bennymeg** [comment]
Please advise the readme file regarding version computability.
v20 is not released yet.
