### ISSUE TITLE
Update to Support Nx 20

### ISSUE THREAD

**Issue by ferenc-a** [bennymeg/nx-electron#313]
Nx 20 has been out for over a month: https://nx.dev/blog/announcing-nx-20.
According to the [compatibility section of the readme](https://github.com/bennymeg/nx-electron?tab=readme-ov-file#compitability), for Nx 20 I should use version 20 of this package, but that doesn't exist yet.

See also: https://github.com/bennymeg/nx-electron/issues/308, https://github.com/bennymeg/nx-electron/issues/293.

**Comment by conor-mac-aoidh** [comment]
https://github.com/bennymeg/nx-electron/pull/315

**Comment by glani** [comment]
20 support was merged but not released to npm. can we release it?

**Comment by krishnakumar797** [comment]
> 20 support was merged but not released to npm. can we release it?

+1 waiting to update through npm.

**Comment by bennymeg** [comment]
Will be published after Ill test it and fix some missing config.
