### ISSUE TITLE
Debug with vscode failed.

### ISSUE THREAD

**Issue by daihere1993** [bennymeg/nx-electron#36]
**Describe the bug**
I've tried to debug electron process follow the document(https://github.com/bennymeg/nx-electron/blob/master/docs/debugging.md). But throw below errors when I execute command `npm run serve:main`

_app name is: electron_

> nx serve --inspect=inspeck-brk electron
> ng run electron:serve --inspect=inspeck-brk
Schema validation failed with the following errors:
  Data path ".inspect" should be equal to one of the allowed values.
  Data path ".inspect" should be boolean.
  Data path ".inspect" should match exactly one schema in oneOf.

**Desktop (please complete the following information):**
 - OS: [WINDOWS]
 - Nx Electron Version [9.2.2]

**Comment by bennymeg** [comment]
I had a typo in the documentation.
Please try to use `--inspect=inspect-brk` instead.
