### ISSUE TITLE
Remove source maps of frontendProject from app.asar

### ISSUE THREAD

**Issue by xXKeyleXx** [bennymeg/nx-electron#38]
**Describe the bug**
When you make the electron app and the frontendProject has sourcemaps these get included into the final app.asar.

**To Reproduce**
1. build a frontend project with sourcemaps (like Angular)
2. run `nx run <project>:make`
3. extract app.asar (`npx asar extract app.asar unpacked`)
4. See source maps in frontendProject folder

**Expected behavior**
Sourcemaps shoul be excluded

**Desktop (please complete the following information):**
 - OS: WIN10
 - Nx Electron Version: 9.1.1

**Additional context**
My project consists of an Nest.js, Angular 10 and the Electron part

**Comment by bennymeg** [comment]
Did you built the app for production? and if so, did you disabled source map file generation in 'angular.json' file?

**Comment by xXKeyleXx** [comment]
I did build it for production and I did not disable the sourcemap generation as I want to upload the sourcemaps to Sentry.io

The exclusion for sourcemaps is in the nx-electron code but doesn't seem to affect the frontend files:
https://github.com/bennymeg/nx-electron/blob/master/src/builders/make/make.impl.ts#L118-L123

**Comment by bennymeg** [comment]
I will look into it.

**Comment by bennymeg** [comment]
Please let me know if everything works as expected on version [9.3.1](https://www.npmjs.com/package/nx-electron)

**Comment by xXKeyleXx** [comment]
Looks like the sourcemaps for js files are not included anymore 👍 
But the sourcemaps for css files are still included (`styles.515ea69c35bd61efc1f4.css.map`)

**Comment by bennymeg** [comment]
My bad, it should be fixed now ([9.3.2](https://www.npmjs.com/package/nx-electron)).

**Comment by s4m0r4m4** [comment]
Is this configurable or are the source maps always not included now?

**Comment by bennymeg** [comment]
By default, when you package your app into a single executable all the source map files will be excluded.
If one will wish to include them anyway, it can be done by adding them in the make configuration using the files field.
