### ISSUE TITLE
Trying to generate a project

### ISSUE THREAD

**Issue by kattsushi** [bennymeg/nx-electron#4]
![image](https://user-images.githubusercontent.com/12107518/71651803-1b479e00-2ce6-11ea-9d37-444dcd548e8c.png)
 im trying to generate a project and i getting this issue promt

**Comment by bennymeg** [comment]
Thank you for bringing this to attention, I have fixed the issue.

It appears that I had a bug in my build process that might caused creation of duplicate files in the final package. In the future I will add GitHub actions (CI/CD) to avoid similar bugs in the future.

Could please update the package and verify the bug had been fixed on your side as well?

**Comment by kattsushi** [comment]
Awesome tested and is already fixed, Thanks! count on me to report and testing for future features or bugs! im stay tuned about this awesome project!
