### ISSUE TITLE
wrong tsconfig referenced in eslintrc & other config files

### ISSUE THREAD

**Issue by hallowatcher** [bennymeg/nx-electron#41]
Heads up, when creating a brand new nx project and adding nx-electron into it, it still expects the old naming system for tsconfig files

![image](https://user-images.githubusercontent.com/6265839/89207277-c4c37a80-d5ba-11ea-8317-f572982bb58b.png)

The same goes for the generated `tsconfig.json` file

Furthermore, since the eslintrc is json, the strings here should be double-quoted
![image](https://user-images.githubusercontent.com/6265839/89207362-e58bd000-d5ba-11ea-8c4c-4a975ff03051.png)

Repro steps:
`npx create-nx-workspace@latest`
`npm install -D nx-electron`
`nx g nx-electron:app <electron-app-name> --frontendProject=<frontend-app-name>`

-> check .eslintrc file & tsconfig file

**Comment by bennymeg** [comment]
Hi,

About the single quotes, I believe that is an issue on NX. if you will look at the following snippets from @nrwl/workspace:
https://github.com/nrwl/nx/blob/920328ca7121b1b9ce1a702542905475023e256c/packages/workspace/src/utils/lint.ts#L237-L243
I think you should open a new issue on `@nrwl/nx` repository.

About the 'tsconfig.base.json':
https://github.com/nrwl/nx/blob/920328ca7121b1b9ce1a702542905475023e256c/packages/workspace/src/utils/lint.ts#L233
It got updated when they switched to angular 10, hence it will be fixed on `nx-electron` version 10 as well.
