### ISSUE TITLE
Electron version 7 instead of 9 

### ISSUE THREAD

**Issue by itapai** [bennymeg/nx-electron#45]
**Describe the bug**
When creating a new electron app, the electron version is 7.1.0 instead of 9.0.5

**To Reproduce**
1. npx create-nx-workspace qwe 
2. cd qwe
3. npm i -D nx-electron
4. nx g nx-electron:app test

**Expected behavior**
Electron version in package.json should be 9

**Desktop (please complete the following information):**
 - OS: arhclinux
 - Node Version: 14.7.0
 - Nx Electron Version: 9.3.2

**Comment by bennymeg** [comment]
Tnx, I've updated it.
It will be fixed on the next release.
