### ISSUE TITLE
Specify Output Path for nx make

### ISSUE THREAD

**Issue by s4m0r4m4** [bennymeg/nx-electron#48]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to specify the output path of the `nx make` command, for use in build automation pipelines.

**Describe the solution you'd like**
nx make --outputPath="C:\...\...\..." --deleteOutputPath=true/false (similar to the way angular CLI allows you to override)

**Describe alternatives you've considered**
Right now the "out" param in angular.json is used to set the 'output property in the electron-builder:
`output: join(context.workspaceRoot, options.out)` [line 116 of make.impl.ts]. But i have not found a way to specify this from the command line.

**Comment by bennymeg** [comment]
Ill take a look, It should not be a problem.

**Comment by s4m0r4m4** [comment]
Hi I see you added this CLI parameter. Is this released?

**Comment by bennymeg** [comment]
Not yet, I was busy lately.
I will try to release an alpha tomorrow so you could test it out.

**Comment by s4m0r4m4** [comment]
Thanks! I'll check it out

**Comment by s4m0r4m4** [comment]
I made a few suggestions here: https://github.com/bennymeg/nx-electron/pull/54

**Comment by bennymeg** [comment]
fixed in 10.0.0-alpha.3
