### ISSUE TITLE
Architecture questions

### ISSUE THREAD

**Issue by ericwooley** [bennymeg/nx-electron#49]
in nx-electron, the builder uses the index.html from  another app, or in dev mode it a url where nx is serving another app. So where would you put the electron code, EG the code for a system tray? https://www.tutorialspoint.com/electron/electron_system_tray.htm

Currently I have a setup like this
```
apps
  - web                        actual application
  - electron                  nx-electron project
  - electron-bridge       nx react application which loads an iframe to web
```
electron bridge has code that looks like this: 
```ts
import { remote } from 'electron'
import path from 'path'

const { Tray, Menu } = remote

let trayIcon = new Tray(path.join('', './assets/logo.png'))
const trayMenuTemplate = [
  {
    label: 'Empty Application',
    enabled: false,
  },

  {
    label: 'Settings',
    click: function () {
      console.warn('Clicked on settings')
    },
  },

  {
    label: 'Help',
    click: function () {
      console.warn('Clicked on Help')
    },
  },
]

let trayMenu = Menu.buildFromTemplate(trayMenuTemplate)
trayIcon.setContextMenu(trayMenu)

```

However, webpack (predictably) errors when you try to serve electron code: 
```
ERROR in /home/ericwooley/tengable/node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in '/home/ericwooley/tengable/node_modules/electron'
```

### Now the actual question
What architecture is recommended? Do you just use a .js file in assets? Do you modify the nx webpack config in some way?

**Comment by ericwooley** [comment]
I ended up just needing a preload script. Seemed easy enough.

**Comment by bennymeg** [comment]
Sorry for the late response.
I do not think that separating it tot two different electron apps is the right way to go.
I tend to keep system tray, splash screens etc. as a separate window on the main js file in `nx-electron` generated project.
In case you need to serve separate html file (i.e. for splash screen) and your front end is serving a single page application, I create  a static html file on the assets folder and point the window object to it.
