### ISSUE TITLE
When you use this plugin you must install `typescript`.

### ISSUE THREAD

**Issue by Reidond** [bennymeg/nx-electron#50]
**Describe the bug**
I created nx workspace and some apps including one with nx-electron plugin

**To Reproduce**
1. Create nx workspace
2. Make some apps
3. Create nx-electron app
4. nx serve app-electron
5. See error

**Expected behavior**
I expected to see electron app to popup

**Screenshots**
<img width="557" alt="Screenshot 2020-09-09 at 17 41 20" src="https://user-images.githubusercontent.com/20406775/92613474-b1938100-f2c3-11ea-8926-8ce6fa2c7fe3.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Nx Electron Version 9.3.2

**Comment by Reidond** [comment]
[Repository with problem](https://github.com/testing-student-app/stract2)

**Comment by Reidond** [comment]
After some debug i found what causes error: ForkTsCheckerWebpackPlugin
https://github.com/bennymeg/nx-electron/blob/174497a9ac735b50bdc2bb96a1477c4174a784ef/src/utils/config.ts#L62-L65

**Comment by bennymeg** [comment]
Hi, do you mind trying to install typescript globally?

**Comment by Reidond** [comment]
Same error after installing typescript globally

**Comment by Reidond** [comment]
It's strange error because, for example, vue with typescript also has this plugin in webpack, but error does not happen there

**Comment by bennymeg** [comment]
Hi, I could not reproduce this issue on my machine.
Did you managed to find what went wrong with your project?

**Comment by Reidond** [comment]
Hi, yes i will close the issue
