### ISSUE TITLE
Running source in Mac OS

### ISSUE THREAD

**Issue by esakal** [bennymeg/nx-electron#51]
**Is your feature request related to a problem? Please describe.**
I tried to run the source code in Mac and failed, it seems that your devop scripts are tight to Microsoft.

**Describe the solution you'd like**
Be able to run the sources in Mac OS

**Comment by bennymeg** [comment]
Hi,
Well I develop on windows..

To migrate the build commands you can replace all the `xcopy` & `del` commands with  `cp -r` & `rm -rF` respectively.

About the script, all that it is doing is to update the private field on the compiled `package.json` from true to false.
It can be easily replaced with a simple _sed_ command, I believe something like that will do the work:
```sed -i 's/^\("private":\) true/\1 false/' build/package.json```
