### ISSUE TITLE
Can I use nx-electron without specifying frontend project?

### ISSUE THREAD

**Issue by pointbre** [bennymeg/nx-electron#52]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can I use nx-electron without specifying frontend project?

I'm thinking of creating electron app that embeds nestjs server which hosts static files that webpack builds from another Angular project. The thing is I don't want the electron app to load what webpack builds from another Angular project but want to use static files the embedded nestjs server hosts. This way, I can get separate frontend project from electron build and from nestjs build too.

**Describe alternatives you've considered**

**Additional context**

**Comment by bennymeg** [comment]
Hi,
If I understood you correctly, I believe it is possible (I did not tried it).

In your `app.ts` file replace the line that loads the frontend project with a URL to your statically served files.
Make sure your compiled server is loaded into the app bundle (in the make configuration file).
Don't forget to run your server before the main window is ready to load.

Hope this helps,
Good luck.

**Comment by pointbre** [comment]
Thanks
