### ISSUE TITLE
NPM release contains a lot of dev stuff

### ISSUE THREAD

**Issue by s4m0r4m4** [bennymeg/nx-electron#53]
**Describe the bug**
The released NPM package contains a lot of development/testing code that is not necessary:
- the nx-electron package contains it's own full node_modules folder
- there are many files with the *.spec.ts and *.spec.js extensions, clearly for testing only
- the typescript source files (*.ts) are shipped in addition to the typings files (*.d.ts)

**Expected behavior**
I do not believe released NPM packages are supposed to contain those sorts of artifacts. The size of this package would be considerably reduced if those were removed. I've never shipped an NPM package before, but looking at other ones I don't see a node_modules subfolder, instead use peer dependencies to specify which packages you require. I'm also relatively certain you can get rid of all testing scripts and the typescript source code -> so in the end you'll only be shipping plain javascript and typescript source files.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nx Electron Version: v10.0.0-alpha.1

Thanks for a great NX package, this makes Electron applications in nx work great!

**Comment by bennymeg** [comment]
Thanks for letting me know.
I guess my build script failed during clean up, I'll take a look.
