### ISSUE TITLE
Question about the generated Electron app architecture

### ISSUE THREAD

**Issue by dannymcgee** [bennymeg/nx-electron#55]
Hi there, thanks for putting this together!

I'm working on my first Electron project and about to start fleshing out the Electron-specific functionality (multiple windows and such), but I'm curious as to why the generated Electron app is organized into classes with all static methods and properties. I'm not all that familiar with the `static` keyword in TypeScript. Is it a bad idea to use standard class instances in Electron for some reason? Is it just for organization (i.e. equivalent to using namespaces)?

**Comment by bennymeg** [comment]
Just a common practice when writing a desktop application.
Since this is a desktop application, the entry class is going to need a static entry method.
I injected the app / browser window into the main() method in order to make it more testable.
