### ISSUE TITLE
Linux chrome sandbox permissions

### ISSUE THREAD

**Issue by phcollignon** [bennymeg/nx-electron#56]
You could add to the troubleshooting section that some permissions have to be set on the chrome-sandbox folder (on Linux Debian 10) : 
```
sudo chown root:root ./angular-electron/node_modules/electron/dist/chrome-sandbox
sudo chmod 4755 ./angular-electron/node_modules/electron/dist/chrome-sandbox

```

**Comment by bennymeg** [comment]
Thanks,
Can you please describe what error do you see if you do not set these permissions so I can explain it in the documentation?

**Comment by atali** [comment]
I have the same issue, can we use a postinstall in the package.json to change those permission ?

**Comment by bennymeg** [comment]
That is a Linux only issue, I cannot add it to the post install script since it would fail on windows (but you can add it to your project).
I will add it to the documentation. (some more information about the issue would be nice).

**Comment by phcollignon** [comment]
> Thanks,
> Can you please describe what error do you see if you do not set these permissions so I can explain it in the documentation?

Here it is : 
```
building 44/62 modules 18 active .../router/__ivy_ngcc__/fesm2015/router.js[18817:1104/203439.291599:FATAL:setuid_sandbox_host.cc(158)] **The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/phico/projects/notelink/playground/angular-electron/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.**
/home/phico/projects/notelink/playground/angular-electron/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@8.0.5 electron:serve: `wait-on tcp:4200 && npm run electron:serve-tsc && npx electron . --serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron@8.0.5 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
