### ISSUE TITLE
Is it possible make nx-electron works with electron-react-boilerplate?

### ISSUE THREAD

**Issue by daiwhea** [bennymeg/nx-electron#57]
**Is your feature request related to a problem? Please describe.**
It's the first time to use nx and nx-electron for me. I'm not sure, can I use any other boilerplates such as electron-react-boilerplate to work with nx-electron? 

Or in order to use nx-electron, I must create a react-app for this nx-electron desktop app?

In my react-app, I need to invoke electron api to read/write files. And I don't want a standalone api server.

**Describe the solution you'd like**
If possible, I wish nx-electron can provide some way to work with some other electron-boilerplates.

Thanks for your work.

**Comment by bennymeg** [comment]
> can I use any other boilerplates such as electron-react-boilerplate to work with nx-electron?

No, you cannot.

> Or in order to use nx-electron, I must create a react-app for this nx-electron desktop app?

Yes, you will need to create a react frontend project using Nx schematics.

**Comment by daiwhea** [comment]
Thanks for your clarifying.

**Comment by daiwhea** [comment]
Another question, If I want to read/write files and render it in the react app, is there any method to achieve it?

Or I can only use http api to read/write datas? And nx-electron is a shell [or browser] to load an html page and display it.

Thanks again.

**Comment by bennymeg** [comment]
If you want to access the machine file system you can do it on the (electron) application side using `fs` (or similar package) and then send it to the renderer process via ipc.

On the renderer side you can use only http.

**Comment by daiwhea** [comment]
Ok, I got it. Thanks!
