### ISSUE TITLE
Automatic build before packaging / making

### ISSUE THREAD

**Issue by bennymeg** [bennymeg/nx-electron#6]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to rebuild the project before every time I want to package my project.

**Describe the solution you'd like**
Automatically trigger the build of the `frontendProject` & `backendProject` before packaging/making.
Also, download and compile native packages using `electron-rebuild` before every build.

**Describe alternatives you've considered**
Create a work space schematic that will handle all of the above in a single step.

**Comment by s4m0r4m4** [comment]
+1 to this, good idea! I was running into this very issue today with `nx make <project>`, not realizing that it wasn't actually doing a build step before.
