### ISSUE TITLE
add multiple frontend apps

### ISSUE THREAD

**Issue by itapai** [bennymeg/nx-electron#60]
Right now, only one frontend app can be used with nx-electron. 
Would it be possible to include more than one?

**Comment by bennymeg** [comment]
You can create as many frontend projects as you want, but you can use only one at a time (as it is). you can switch between them by changing the `frontendProject` variable.
If you wish to create multiple browser windows form different frontend projects it can be done by adding a few lines of code.

**Comment by itapai** [comment]
I want to create multiple browser windows, and each window should have it's own frontend app.
I can do that with the `extraFiles` option for electron-builder, right? Is there a better way perhaps?

**Comment by bennymeg** [comment]
I belive the right way to do that is to use the `files` field like so:
```
      {
          from: `./dist/apps/${frontendProject}`,
          to: ${frontendProject},
          filter: ['**/!(*.+(js|css).map)', 'assets']
      }
```

**Comment by itapai** [comment]
Yeah, ended up with something similar. 
Thanks

**Comment by aravindjaimon** [comment]
@itapai Can you explain what you have done to achieve this?
