### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by ericwooley** [bennymeg/nx-electron#67]
**Is your feature request related to a problem? Please describe.**
Not a problem.

I am attempting to help with [this issue](https://github.com/bennymeg/nx-electron/issues/66), but I am a little stuck getting started. All the npm commands fail. It looks like they are maybe written to work in windows?

**Describe the solution you'd like**
It would be awesome to have some development instructions to work with. EG windows, node 14, etc... and the general flow of the workflow when developing.

**Describe alternatives you've considered**
No alternatives

**Additional context**
Thanks for the plugin! It's great.

**Comment by bennymeg** [comment]
First of all, thank you for willing to contribute to this project.

The development process is not as good as I wished it would be, but you are right I should at least explain how one should approach this project if he wish to contribute to it. I will try to get to it this week.
