### ISSUE TITLE
Issues with packaged app

### ISSUE THREAD

**Issue by aldokocha** [bennymeg/nx-electron#71]
My app is working fine in development mode but once packaged IPC stops working. I use contextBridge with apiKey 'electron' as defined in preload.ts file. So while in development mode window['electron' ] is defined on front end side and IPC is working fine but once packaged it's not defined anymore. Is it possible preload.js is not loaded when packaged? Is there any way to verify it?

**Comment by bennymeg** [comment]
> Is it possible preload.js is not loaded when packaged?

Yes, it is. I will check it.

> Is there any way to verify it?

Yes you can. You can set asar=false at your making script and then look for the file on the packaged application.

**Comment by aldokocha** [comment]
I've tried the asar=false option and preload.js is missing in resources. Once it manually added the application is working fine.

**Comment by bennymeg** [comment]
Do you have a `preload.js` file in your _dist_ folder?

**Comment by aldokocha** [comment]
Yes I do, in the dist\apps\electron-app folder and if I copy it
to dist\packages\win-unpacked\resources\app\electron-app folder then
everything works fine

**Comment by bennymeg** [comment]
Should be fixed in `v10.0.3`.
Could you please verify that this fix works for you?

**Comment by aldokocha** [comment]
Works fine now with asar=true. Thanks a lot! I'm working with nx framework for some time now and fell in love with it and really happy to add my electron project to the mix. Keep up the good work!

**Comment by EchopixUser** [comment]
I have the same issue with the newest version. Not sure what could be wrong. preload.js is in dist, but not packaged when making the app. if I do asar=false and copy it to resources, it will work. 

However another issue arises, the **window** object is null. So this `window.addEventListener('DOMContentLoaded', () => {...}` piece of code does not work. I load the file when spawning new window like this:
`

const newWindow = new BrowserWindow({
          webPreferences: {
            contextIsolation: true,
            preload: join(__dirname, 'preload.js'),
            nodeIntegration: true
          },
          kiosk: true,
        });
`
