### ISSUE TITLE
App can not be packaged / made when generated into a subdirectory

### ISSUE THREAD

**Issue by realityfilter** [bennymeg/nx-electron#77]
When generating the electron shell app into a subdirectory packaging and making the app will fail. Also frontend projects in subdirectories will not be packaged correctly.

- nx g nx-electron:app electron --frontendProject frontend --directory project
- nx build project-electron
- nx package project-electron

This will result in an "Error: ENOENT: no such file or directory, open 'dist/apps/project-electron/index.js'".

The actual output path is 'dist/apps/project/electron' and can be read from the workspace build config of the app build config.

This is a problem for the reference of the frontend project, too. If the frontend project resides in a subdirectory it will not get packaged into the app, too. This could be solved by either:

- derive path from root of the frontend project `dist/${root}`
- use output path from build config of the frontend project. But this is different for the actual type (e.g. 'outputPath' for angular and 'dest' for vue)
- let this be configurable

**Comment by bennymeg** [comment]
You need to set the `sourcePath` value to `dist/apps/project` in your packager / maker configuration file (or in your angular / workspace configuration file).

**Comment by realityfilter** [comment]
Thanks. But this would only work if the projects reside in the same subdirectory?

**Comment by bennymeg** [comment]
Yes, the backend project and the frontend project most reside in the same subdirectory.
