### ISSUE TITLE
Missing jshint?

### ISSUE THREAD

**Issue by s4m0r4m4** [bennymeg/nx-electron#78]
**Describe the bug**The contributing docs say to run `npm run lint` prior to submitting a PR, but this command uses jshint, which is not included as a dev dependency in package.json.

I'm pretty sure I just need to add jshint as a devDependency in package.json, is that ok? Is there any version you prefer?

`'jshint' is not recognized as an internal or external command, operable program or batch file.`

**Comment by bennymeg** [comment]
Yes, I have it as a global package, my bad.
Latest would be fine.

**Comment by bennymeg** [comment]
Done.
