### ISSUE TITLE
[Question] How to use static assets?

### ISSUE THREAD

**Issue by Ravi-Rajpurohit** [bennymeg/nx-electron#79]
how can one use static assets in nx-electron? 

tried using [__static](https://webpack.electron.build/using-static-assets) but it didn't work.

Please help.

**Comment by bennymeg** [comment]
Hi,
I did quite understood your question, could you elaborate? (is this a webpack related build time issue, packaging issue, what's happening and what you expect to happen etc..)

**Comment by Ravi-Rajpurohit** [comment]
I have some SVG stored in the assets folder of electron app. I want to use use them in some initialization function.
I am able to use those SVG while serving the app using `path.join(__dirname,'assets/xyz.svg')}"`. 
But when i package the app `path.join(__dirname,'assets/xyz.svg')}"` no longer works. 
The assets don't get bundled with the app is what i think.

So basically `path.join(__dirname,'assets/xyz.svg')}"` this works while serving the app and doesn't work when the app gets packaged to an AppImage (in my case).

**Comment by bennymeg** [comment]
Thanks for clarifying your issue.

 If you wish to add additional files to the packaged app you will need to specify it in the `files` field in the config file.
 you can read more about it [here](https://www.electron.build/configuration/contents#files).
