### ISSUE TITLE
Error when trying to build electron app 

### ISSUE THREAD

**Issue by aldokocha** [bennymeg/nx-electron#8]
Cannot assign to read only property '_showWarnings' of object '#<Object>'
TypeError: Cannot assign to read only property '_showWarnings' of object '#<Object>'
    at TapSubscriber._tapNext (D:\EyeKor\git\Excelsior-NX\excelsior\node_modules\@angular-devkit\core\src\json\schema\visitor.js:56:210)

**Comment by bennymeg** [comment]
Please provide more information (as requested in the issue template):
Steps to reproduce the behavior, packages versions (nx, nx-electron, angular-devkit, angular cli) etc...

**Comment by aldokocha** [comment]
Seems like there's a problem with dependencies. Upgraded @angular/compiler-cli and @angular/cli and the issue resolved.
