### ISSUE TITLE
nx-electron 11: No assets leads to webpack config error

### ISSUE THREAD

**Issue by patdx** [bennymeg/nx-electron#82]
**Describe the bug**

I upgraded an nx-electron app to v11 which was working fine before. It has a config like below:

```
        "build": {
          "builder": "nx-electron:build",
          "options": {
            "externalDependencies": [
              "electron"
            ],
            "main": "apps/desktop-app-main/src/main.ts",
            "outputPath": "dist/apps/desktop-app-main",
            "tsConfig": "apps/desktop-app-main/tsconfig.app.json",
            "webpackConfig": "tools/scripts/webpack/config-desktop-app-main.js"
          },
```

I guess there was previously an assets setting which I deleted since I was not using it.

Seems like even if it is gone, in the builder it is normalized to an empty array. Probably it gets normalized based on this schema.json?

https://github.com/bennymeg/nx-electron/blob/f741582b3f2d7f0075167f91c396f3ede86533c2/src/builders/build/schema.json#L37

So when I run `nx build desktop-app-main`, it checks if `options.assets` is truthy (it is), and tries to init the copy-webpack-plugin.

![image](https://user-images.githubusercontent.com/353863/110888314-42105400-832f-11eb-9b19-ff169340bd6c.png)

Since the array is empty, copy-webpack-plugin throws an error:

```
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be an non-empty array.
```

I can patch the nx-electron builder easily to get the desired result:

```diff
-    if (options.assets) {
+    if (options.assets && options.assets.length >= 1) {
```

Adding any kind of "stub" file/folder to the assets array fixes the issue too 😃

![image](https://user-images.githubusercontent.com/353863/110888537-b9de7e80-832f-11eb-9f4e-caf77f78409d.png)

But I think ultimately, it would be nice to not throw an error if someone does the same thing as I did.

**To Reproduce**

1. Clone this repo: https://github.com/patdx/nx-electron-test
2. Run `npm install` and then `npx nx build main`

Note: I noticed when I tried to reproduce with a fresh workspace above that by default nx-electron inits an empty assets folder, so I guess this would only happen if someone tries to delete the `assets` config line (and forgets about it).

![image](https://user-images.githubusercontent.com/353863/110891336-2314c080-8335-11eb-961a-1f26e35eac87.png)

**Expected behavior**

I expect to be able to build the main app using `nx build desktop-app-main` even if no asset config is specified.

**Screenshots**

I attached some screenshots above.

**Desktop (please complete the following information):**
 - OS: Ubuntu via Windows WSL2
 - Nx Electron Version v11.0.0

**Comment by bennymeg** [comment]
Thank you for the detailed explanation and for fixing the issue!
I will merge it soon.
