### ISSUE TITLE
Platform error in v11

### ISSUE THREAD

**Issue by s4m0r4m4** [bennymeg/nx-electron#84]
**Describe the bug**
When I try to package/make my electron app after upgrading to nx-electron v11 I get the following error for the "make" command:

```
Property 'platform' does not match the schema.
{
  "oneOf": [
    {
      "type": "string",
      "enum": [
        "windows",
        "mac",
        "linux"
      ]
    },
    {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "windows",
          "mac",
          "linux"
        ]
      }
    }
  ],
  "default": null,
  "description": "Target platform/s."
}'

```

**To Reproduce**
I was able to make a new nx application, following the steps in the README, and the `make` command threw the same error.

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nx Electron Version: 11.0.0

**Comment by s4m0r4m4** [comment]
If I remove the "package" entry in the schema.json file under src/builders/package (modifying the nx-electron plugin), then an error is thrown about `arch` not matching the schema. If I remove the `arch` entry too, then an error about `publicPolicy` is thrown. So it seems like whatever data is getting passed through the schema isn't even close to what the schema expects.

**Comment by s4m0r4m4** [comment]
If I simply delete the `arch`, `platform`, and `publishPolicy` entries from the schema.json file, the builder seems to work just fine.

**Comment by bennymeg** [comment]
That happened to me before.
I did not change this types over the lase couple of releases.
Might just be mismatch in the devkit version, what version do you use in your project?

**Comment by s4m0r4m4** [comment]
```
Angular CLI: 11.2.0
Node: 14.16.0
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1102.4
@angular-devkit/build-angular    0.1102.4
@angular-devkit/core             10.1.7
@angular-devkit/schematics       10.1.7
@angular-devkit/schematics-cli   0.1001.7
@angular/cdk                     11.0.0
@angular/material                11.0.0
@schematics/angular              11.2.4
@schematics/update               0.1102.0
rxjs                             6.6.6
typescript                       4.1.5
```

**Comment by s4m0r4m4** [comment]
```
  nx : Not Found
  @nrwl/angular : 11.5.1
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/node : 11.5.1
  @nrwl/tao : 11.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.1
  typescript : 4.1.5
```

**Comment by s4m0r4m4** [comment]
OH! I was on an old version of  "@angular-devkit/schematics-cli". Apparently nx does not update that when you do `nx migrate`. 

After updating to the latest version, my app built successfully. Thank you for the quick and helpful response, good work as always!

**Comment by s4m0r4m4** [comment]
Ok I spoke too soon. After upgrading "@angular-devkit/schematics-cli", the build worked. But now a colleague tried cloning the repo (including package-lock.json), running `npm install`, and the build breaks with that same error above. I get the same error too when I clone a new copy of the repo. Can you share which versions are working for you (package and package-lock)?

**Comment by bennymeg** [comment]
<details>
  <summary>package.json</summary>
<pre>
<code>
    "@angular-devkit/build-angular": "^0.1102.4",
    "nx-electron": "^11.0.2",
</code>
</pre>
</details>


<details>
  <summary>package-lock.json</summary>
<pre>
<code>
    "@angular-devkit/architect": {
      "version": "0.1100.7",
      "resolved": "https://registry.npmjs.org/@angular-devkit/architect/-/architect-0.1100.7.tgz",
      "integrity": "sha512-b2zv2yiRbdhJ7hJfZsAvGYcqgh2DVtc7gRIPo1eDPvOAKrenmZ4zo/v0PRYScrTsPzqmoCokNA5nIwufwUEnuA==",
      "dev": true,
      "requires": {
        "@angular-devkit/core": "11.0.7",
        "rxjs": "6.6.3"
      },
      "dependencies": {
        "@angular-devkit/core": {
          "version": "11.0.7",
          "resolved": "https://registry.npmjs.org/@angular-devkit/core/-/core-11.0.7.tgz",
          "integrity": "sha512-1GKnIT++YSUHpzzRx9QC0+8yOw4wy+ZpiJVDlroPSeK4FGrTCJqJKenkfRjVFRFOSrzTiJds+IU6kI4+bFbw9g==",
          "dev": true,
          "requires": {
            "ajv": "6.12.6",
            "fast-json-stable-stringify": "2.1.0",
            "magic-string": "0.25.7",
            "rxjs": "6.6.3",
            "source-map": "0.7.3"
          }
        }
      }
    },
    "@angular-devkit/build-angular": {
      "version": "0.1102.4",
      "resolved": "https://registry.npmjs.org/@angular-devkit/build-angular/-/build-angular-0.1102.4.tgz",
      "integrity": "sha512-/t39b+fXDG5kwJGovtGF6K4Vg55BvVz2IJbeVurpplg2pJp5cpSUhQAe0mXcvjkvle/ZLIfYP0Ahdh/7VahuGg==",
      "dev": true,
      "requires": {
        "@angular-devkit/architect": "0.1102.4",
        "@angular-devkit/build-optimizer": "0.1102.4",
        "@angular-devkit/build-webpack": "0.1102.4",
        "@angular-devkit/core": "11.2.4",
        "@babel/core": "7.12.10",
        "@babel/generator": "7.12.11",
        "@babel/plugin-transform-async-to-generator": "7.12.1",
        "@babel/plugin-transform-runtime": "7.12.10",
        "@babel/preset-env": "7.12.11",
        "@babel/runtime": "7.12.5",
        "@babel/template": "7.12.7",
        "@jsdevtools/coverage-istanbul-loader": "3.0.5",
        "@ngtools/webpack": "11.2.4",
        "ansi-colors": "4.1.1",
        "autoprefixer": "10.2.4",
        "babel-loader": "8.2.2",
        "browserslist": "^4.9.1",
        "cacache": "15.0.5",
        "caniuse-lite": "^1.0.30001032",
        "circular-dependency-plugin": "5.2.2",
        "copy-webpack-plugin": "6.3.2",
        "core-js": "3.8.3",
        "critters": "0.0.7",
        "css-loader": "5.0.1",
        "cssnano": "4.1.10",
        "file-loader": "6.2.0",
        "find-cache-dir": "3.3.1",
        "glob": "7.1.6",
        "https-proxy-agent": "5.0.0",
        "inquirer": "7.3.3",
        "jest-worker": "26.6.2",
        "karma-source-map-support": "1.4.0",
        "less": "4.1.1",
        "less-loader": "7.3.0",
        "license-webpack-plugin": "2.3.11",
        "loader-utils": "2.0.0",
        "mini-css-extract-plugin": "1.3.5",
        "minimatch": "3.0.4",
        "open": "7.4.0",
        "ora": "5.3.0",
        "parse5-html-rewriting-stream": "6.0.1",
        "pnp-webpack-plugin": "1.6.4",
        "postcss": "8.2.4",
        "postcss-import": "14.0.0",
        "postcss-loader": "4.2.0",
        "raw-loader": "4.0.2",
        "regenerator-runtime": "0.13.7",
        "resolve-url-loader": "3.1.2",
        "rimraf": "3.0.2",
        "rollup": "2.38.4",
        "rxjs": "6.6.3",
        "sass": "1.32.6",
        "sass-loader": "10.1.1",
        "semver": "7.3.4",
        "source-map": "0.7.3",
        "source-map-loader": "1.1.3",
        "source-map-support": "0.5.19",
        "speed-measure-webpack-plugin": "1.4.2",
        "style-loader": "2.0.0",
        "stylus": "0.54.8",
        "stylus-loader": "4.3.3",
        "terser": "5.5.1",
        "terser-webpack-plugin": "4.2.3",
        "text-table": "0.2.0",
        "tree-kill": "1.2.2",
        "webpack": "4.44.2",
        "webpack-dev-middleware": "3.7.2",
        "webpack-dev-server": "3.11.2",
        "webpack-merge": "5.7.3",
        "webpack-sources": "2.2.0",
        "webpack-subresource-integrity": "1.5.2",
        "worker-plugin": "5.0.0"
      },
      "dependencies": {
        "@angular-devkit/architect": {
          "version": "0.1102.4",
          "resolved": "https://registry.npmjs.org/@angular-devkit/architect/-/architect-0.1102.4.tgz",
          "integrity": "sha512-A/nc/s9S9+H6xFOxcXqyfiCg9lXzCpO2ZVeaNamZB8f8tHoGfFMQ3JkCGhFiYsbze4fXhcwszNq1o36lGIW7FA==",
          "dev": true,
          "requires": {
            "@angular-devkit/core": "11.2.4",
            "rxjs": "6.6.3"
          }
        },
        "@angular-devkit/core": {
          "version": "11.2.4",
          "resolved": "https://registry.npmjs.org/@angular-devkit/core/-/core-11.2.4.tgz",
          "integrity": "sha512-98mGDV4XtKWiQ/2D6yzvOHrnJovXchaAN9AjscAHd2an8Fkiq72d9m2wREpk+2J40NWTDB6J5iesTh3qbi8+CA==",
          "dev": true,
          "requires": {
            "ajv": "6.12.6",
            "fast-json-stable-stringify": "2.1.0",
            "magic-string": "0.25.7",
            "rxjs": "6.6.3",
            "source-map": "0.7.3"
          }
        },
</code>
</pre>
</details>

This is probably not related to `nx-electron`, and still related to devkit versions mismatch (maybe global package?)

**Comment by s4m0r4m4** [comment]
I don't have any globals installed, but who knows. You're probably right about it not being nx-electron related, I'll close this out for the time being.
