### ISSUE TITLE
Partial 'package.json' support

### ISSUE THREAD

**Issue by bennymeg** [bennymeg/nx-electron#88]
**Description**
Add support for packaging using _automatically generated_ partial `package.json` support.
This should reduce greatly the artifact size in many cases.

**Additional context**
This should be used in conjunction with `generatePackageJson` option during build time.

**Rational**
NX-ELECTRON projects are mainly divided into two parts: frontend and backend. 
Due to the nature of a monorepo project, only single 'package.json' file exists in the repository. 
Modern front end platforms (e.g. angular) can overcome this issue by picking and bundling only the dependencies that are in use.  
However, that's is not always the case with electron applications development. 
Moreover, since electron application might use native dependencies, such tools can't be used since it is not recommended to bundle the backend project into single file. 
Hence, we have a `node_modules` folder in the generated package, and since the dependencies tree can be huge, this reflects in the packaged app size. 

On v11 we have added the functionality to dynamically generate dependencies tree to the electron backend project. 
We can take leverage of this functionality in order to shake the dependency tree for the backend project.

**Comment by ronnetzer** [comment]
To add to what you've wrote,
it is essential to merge the existing package.json with the auto-generated one, so it will be bundled with the correct name, author etc. And in order to correctly support auto-updates, the version should be taken from the root package.json

Thanks for the great plugin.

**Comment by Crikey-Mikey** [comment]
This feature would be great. Are there any plans to add this? It would also allow a version from the partial package.json rather than using the nx root package.json for versioning. Unless I'm missing something?

**Comment by bennymeg** [comment]
Added on v12.
Take a look at `generatePackageJson` and `impliciteDependencies` options.
