### ISSUE TITLE
Frontend application not working or empty after initial bootstrapping

### ISSUE THREAD

**Issue by navrocky** [bennymeg/nx-electron#89]
**Describe the bug**
First I create workspace with any type of web app and then create electron app as described in README. Then I tried to serve electron app and see clear white window, then I tried to build app and see no frontend files in `dist/apps/electron`.

Then I tried to build first frontend app in debug and prod mode, and get the same result of serve and build electron app.

I cannot undestand which additional steps should to do to serve or build my electron+frontend app.

**To Reproduce**
```
WORKSPACE_NAME=nx-electron-demo
npx create-nx-workspace@11 ${WORKSPACE_NAME} --preset=react --appName=frontend --style=css --linter=eslint --nx-cloud=false

cd ${WORKSPACE_NAME}
npm install -D nx-electron
nx g nx-electron:app electron --directory= --frontendProject=frontend

nx serve electron
```

**Expected behavior**
After `nx serve electron` I think that I will see electon app with my frontend app inside.

**Desktop (please complete the following information):**
 - OS: OpenSuse Thumbleweed
 - Nx Electron Version 11
 - node --version v10.23.3

**Comment by bennymeg** [comment]
Looks like you forgot to serve your frontend application before you served the backend application.

**Comment by navrocky** [comment]
Its great! I tried with this and its work: 
```
nx run-many --target=serve --projects=frontend,electron --parallel
```
But what about building a package? Do I need to manual copy compiled sources of frontend to somewhere in `dist/electron` ?

And what about to cover these nuances in README.md? I mean how to serve all together, how to build with frontend?

**Comment by shlajin** [comment]
You build it first 
```
nx build electron --prod
nx build renderer --prod --baseHref="./"
```

then you make package it into the electron

```
nx run electron:make
```

**Comment by navrocky** [comment]
Thank you, `--baseHref="./"` helps me a lot. Now it works.
