### ISSUE TITLE
Property 'platform' does not match the schema. (again?)

### ISSUE THREAD

**Issue by shlajin** [bennymeg/nx-electron#90]
**Describe the bug**
I followed the readme to create a new application.
`nx serve myapp` opens electron window, works flawlessly. Yet if I try to build (or package) it, I get the error:
```
> nx run shwarma:make
Property 'platform' does not match the schema.
{
  "oneOf": [
    {
      "type": "string",
      "enum": [
        "windows",
        "mac",
        "linux"
      ]
    },
    {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "windows",
          "mac",
          "linux"
        ]
      }
    }
  ],
  "default": null,
  "description": "Target platform/s."
}'
```
I also tried to pass `--platform=mac,win` during electron app generation (alongside `--frontendProject`), no effect.

**To Reproduce**
Follow steps from readme file, then try to package the app.

**Expected behavior**
The app gets packaged.

**Desktop (please complete the following information):**
 - OS: Mac
 - nx workspace version: 11.6.3
 - Nx Electron Version 11.0.2

**Additional context**
This one is related https://github.com/bennymeg/nx-electron/issues/84 (but there's nothing special in my setup / no upgrade, fresh file and I follow the readme file)
And this one https://github.com/bennymeg/nx-electron/issues/85 (yet the commit didn't help, apparently)

**Comment by shlajin** [comment]
Inspired by discussions in linked issues, I tried to remove  `publishPolicy`, `arg`, `platform` from the `nx-electron` (`builders/package/schema.json`) and it made the app compile

**Comment by bennymeg** [comment]
I've merged the PR but I did not released a new version yet. That's why this properties are still required.

**Comment by shlajin** [comment]
I could have sworn I double checked that the `default: null` wasn't there when I removed stuff from `schema.json`.
Well, apparently I messed that check up, they are indeed not yet published. I guess that's it, thank you :D
