### ISSUE TITLE
[Question] How To Add An App Icon

### ISSUE THREAD

**Issue by Figments** [bennymeg/nx-electron#94]
hello! thank you for the great library.

i'm having an issue figuring out how to add an app icon to my fully-built executable. i tried following all the relevant instructions on here and in the electron.build docs, but i haven't gotten any closer to solving it, i.e. the `make` process says that the default Electron icon is used because the application icon is not set.

how would i go about fixing this?

**Comment by bennymeg** [comment]
try using this configuration on your maker configuration file:
```
    "win": {
        "icon": "apps\\<app-name>\\src\\assets\\icons\\<icon>.ico"
    }
```

**Comment by t-mish** [comment]
That's should be in docs. Thanks

**Comment by bennymeg** [comment]
That is managed by `electron-builder`, and it is written in their docs.

**Comment by t-mish** [comment]
The point is that when you have configs in maker.options.json they are eventually being compiled into electron builder's yaml file. And user must know that the path to all your resources should be according to the workspace root (not relative to maker.options.json file). I think it's a source of confusion.
