### ISSUE TITLE
[Question] Running unit tests for generated electron project

### ISSUE THREAD

**Issue by JulianLang** [bennymeg/nx-electron#98]
Hi, thanks for this great project! :)

I followed the guide from https://www.npmjs.com/package/nx-electron
and then tried to run tests for the generated electron project by running:

`$ nx run application:test`

I am new to `@nrwl/nx` so maybe I just ran the wrong command or didn't understand how to interact with it, but it tells me that 

```
The specified command ("application:test") is invalid. For a list of available options,
run "ng help".
```

So my question is how to run tests for the electron project? Is there anything I need to add manually after following the guide from npm?

Thanks in advance :)

**Comment by bennymeg** [comment]
Hi,
you can use the following command: `nx run-many --target=test --projects=<frontend-app-name>,<electron-app-name> --parallel`.

I have updated the readme accordingly.

**Comment by JulianLang** [comment]
Hi,
thanks a lot, that solved my issue!
So I guess I can close this then. :)
