### ISSUE TITLE
Flow of packaging an app

### ISSUE THREAD

**Issue by Narven** [bennymeg/nx-electron#99]
First thanks for this nx-plugin.

I'm currently having some problems understanding the flow of how we are supose to package the 2 apps (react and electron) together.

I have the electron app called `desktop` and the react called `frontend`.

what I'm currently trying to run is:

* `yarn nx run frontend:build`
* `yarn nx run desktop:build --prod`
* `yarn nx run desktop:package_darwin_x64 --publishPolicy=always --frontendProject=frontend`

My builder for the desktop is:

```json
"package_darwin_x64": {
          "builder": "nx-electron:make",
          "options": {
            "dmg": {
              "background": "icons/background.jpg"
            },
            "appId": "com.company.project"
            "extends": null,
            "name": "desktop",
            "sourcePath": "dist/apps",
            "frontendProject": "frontend",
            "outputPath": "dist/executables/darwin",
            "platform": "mac",
            "arch": "x64",
            "publishPolicy": "always",
            "prepackageOnly": false,
            "mac": {
              "asar": true,
              "icon": "icons/icon.icns"
            }
          }
        },
```

I've already tried several combinations, but what I always get is a app that I can install but I shows only the `desktop` part side, but never "bundles" the `frontend`

What I'm I doing wrong? Is this the flow? What is missing?

**Comment by Narven** [comment]
Thanks to the PR https://github.com/bennymeg/nx-electron/pull/91 I've manage to package it both apps.

**Comment by bennymeg** [comment]
I'll update the documentation to be more clear about this issue
